### ISSUE TITLE
Scrolling using vim-smoothie lags when lualine.nvim is enabled

### ISSUE THREAD

**Issue by bool3max** [hoob3rt/lualine.nvim#1]
* `nvim --version`: 

```
NVIM v0.5.0-dev+972-g84faeb07d
Build type: RelWithDebInfo
LuaJIT 2.0.5
```
* latest versions of both plugins
* terminal: `kitty 0.19.3` (also occurs in xterm)

Scrolling using vim-smoothie while lualine.nvim is enabled produces lag, especially towards the end of the scrolling motion.  This does not occur while using vim-airline (though lualine.nvim is the first statusline plugin I've ever used, but I had to test with another one).

**Comment by bool3max** [comment]
It is less noticeable using the default scroll speed (`let g:smoothie_update_interval=10`), but when using `let g:smoothie_update_interval=5`, a slower scroll speed it becomes immediately apparent. The last few last to-be-scrolled take a second to go by.

**Comment by hoob3rt** [comment]
This does not happen on my system unless I set `g:smoothie_update_interval=1`, even on xterm.
Keep in my that `vim-smoothie` is really cpu heavy as shown below
![screen](https://user-images.githubusercontent.com/41551030/103386159-d4110a80-4afd-11eb-83ed-cfea720747fa.png)
But no lag happens when `lualine.nvim` is not installed so this is definitely an issue, I will try to resolve this asap.

**Comment by bool3max** [comment]
Yeah the less delay between update the more lag there is, without lualine I can get a very smooth motion with it set to `5`, with it not so much. I love the plugin, hope you get it resolved!

**Comment by hoob3rt** [comment]
can you try setting up lualine this way?
```lua
require('lualine').sections = {
  lualine_a = { 'mode' },
  -- lualine_b = { 'branch' },
  lualine_c = { 'filename' },
  lualine_x = { 'encoding', 'fileformat', 'filetype' },
  lualine_y = { 'progress' },
  lualine_z = { 'location'  },
}
```
I think the branch function might be a problem

**Comment by bool3max** [comment]
Using that I get this: 

![image](https://user-images.githubusercontent.com/12991998/103386809-e9d3ff00-4b00-11eb-8808-7b9f547c0fc8.png)

**Comment by hoob3rt** [comment]
try this way
```lua
    local lualine = require('lualine')
    lualine.sections = {
      lualine_a = { 'mode' },
      -- lualine_b = { 'branch' },
      lualine_c = { 'filename' },
      lualine_x = { 'encoding', 'fileformat', 'filetype' },
      lualine_y = { 'progress' },
      lualine_z = { 'location'  },
    }
    lualine.status()
```

**Comment by bool3max** [comment]
Yeah that works, it doesn't lag anymore!

**Comment by hoob3rt** [comment]
Great! Thanks for pointing that out. I know why this is happening but I have a more universal fix in mind than just fixing the `branch` function.

Some functions like `branch`, `fileformat` should probably only run once per file, not on every update like this is happenig like now. 
I will try to resolve this next friday. You can keep using `lualine` without the branch functionality for now or try creating a pr.

**Comment by eric-hansen** [comment]
I'm not super familiar with the Lua API but why not make the calls async with vim.loop instead?

**Comment by hoob3rt** [comment]
> I'm not super familiar with the Lua API but why not make the calls async with vim.loop instead?

Yes function like `branch` have to be made async as well. Thanks for pointing `vim.loop` out, it looks like it could be an easy to implement solution.

**Comment by hoob3rt** [comment]
could you confirm if https://github.com/hoob3rt/lualine.nvim/tree/async solves this issue?

**Comment by bool3max** [comment]
yeah, seems to be fixed, nice.
