### ISSUE TITLE
cursor blinks very quickly

### ISSUE THREAD

**Issue by Stanislav-Lapata** [hoob3rt/lualine.nvim#10]
the cursor blinks very quickly in insert mode

https://user-images.githubusercontent.com/12072329/103450890-beead600-4ccd-11eb-8f39-ec0bb2a26b03.mov

<details>
<summary>my config</summary>

```lua
return function()
  local lualine = require('lualine')
  lualine.theme = 'gruvbox'
  lualine.separator = '/'
  lualine.sections = {
    lualine_a = { 'mode' },
    lualine_b = { 'filename' },
    lualine_c = {  },
    lualine_x = {  },
    lualine_y = { 'branch' },
    lualine_z = { 'filetype'  },
    lualine_diagnostics = {  }
  }
  lualine.inactiveSections = {
    lualine_a = { 'mode' },
    lualine_b = { 'filename' },
    lualine_c = {  },
    lualine_x = {  },
    lualine_y = { 'branch' },
    lualine_z = { },
    lualine_diagnostics = {  }
  }
  lualine.extensions = { 'fzf' }
  lualine.status()
end
```

</details>

**Comment by manimax3** [comment]
Try it without the 'branch' secions which solved the issue for me.

I don't know why but the call to vim.fn.systemlist in the branch module seems to cause the cursor flickering.
If you have vim-fugitive installed I use this as a temporary solution:
```lua
lualine.sections.lualine_b = { function() 
    return vim.fn["fugitive#head"]()
end }
```

**Comment by hoob3rt** [comment]
Yes, the branch function is causing problems for now. This may be related as well. I will try to fix it today.

**Comment by Stanislav-Lapata** [comment]
@hoob3rt in Insert mode 
https://github.com/hoob3rt/lualine.nvim/blob/master/lua/lualine.lua#L60 called cyclic

**Comment by hoob3rt** [comment]
could you confirm if https://github.com/hoob3rt/lualine.nvim/tree/async solves this issue?

**Comment by hoob3rt** [comment]
> @hoob3rt in Insert mode
> https://github.com/hoob3rt/lualine.nvim/blob/master/lua/lualine.lua#L60 is called cyclically
> https://user-images.githubusercontent.com/12072329/103457223-380a1d80-4d0e-11eb-9a46-c831f66f994c.mov
> is it OK?

Yes that should be okay, otherwise things like cursor position or file location won't be updated in insert mode.

**Comment by manimax3** [comment]
@hoob3rt thanks, this fixed the issue. at least on my side
