### ISSUE TITLE
refactor all components with options

### ISSUE THREAD

**Issue by hoob3rt** [hoob3rt/lualine.nvim#100]
I would change this to look cleaner. 
```lua
if options.colored == nil then options.colored = true end
```
and work with options variables. Similar to all other option variables. 
This has two benefits
* while looking at the code you instantly know that `if options.colored` refers to an option. `if colored` can be a local variable
* no additional memory usage

_Originally posted by @hoob3rt in https://github.com/hoob3rt/lualine.nvim/pull/61#discussion_r577801262_

This needs to be done on the whole codebase

**Comment by shadmansaleh** [comment]
I donn't think there is any point in doing this . The components that donn't meed to hold onto some form of state or doesn't provide any special options doesn't need restructuring . The components that currently donn't have options are extreamly simple they donn't need more complexcity . Also even if we change them it will be just returning the same function from an init function . I think we should add that structure to these components when they need them till then leave them alone .

**Comment by shadmansaleh** [comment]
Oh I think I missunderstood what this issue was about 😄 . I thought you ment to add option structures to components that fonn't explicity have them like mode component . My bad now I see you ment to change the veriables created created in components to store options👍

**Comment by shadmansaleh** [comment]
Now I see there was only one component tochange and you've already done it 👍
