### ISSUE TITLE
Update screenshots in README.md

### ISSUE THREAD

**Issue by shadmansaleh** [hoob3rt/lualine.nvim#106]
Since component separators were added we should update the screenshots in README.md as that's the landing page . THEMES.md can be updated too though that will be good amount of work . @hoob3rt didn't you say you had a script for screenshots?

May be update the screenshot when diagnostics is added :) . What do you think?

**Comment by hoob3rt** [comment]
I've got a script ready to create screenshots of the same size in bspwm. WIll do after I merge #95

**Comment by hoob3rt** [comment]
Should be done with https://github.com/hoob3rt/lualine.nvim/commit/41e670af39ecede258e9e895bfc8d20f812b8916 and https://github.com/hoob3rt/lualine.nvim/commit/3ae9a2a483cbbfed6038b94f3817112a06518150

**Comment by shadmansaleh** [comment]
I'm not sure what you did in THEMES.md but the screenshots donn't have section separators ... Did you plan to add them ?

**Comment by hoob3rt** [comment]
I updated all screenshots in THEMES.md to be the same size and same config to look cleaner and changed screenshots in README.md to reflect different possible configurations. I don't see an issue here

**Comment by shadmansaleh** [comment]
No issue . I thought your script was gona take new screenshot . Seems thats not the case 😅.

**Comment by hoob3rt** [comment]
> No issue . I thought your script was gona take new screenshot . Seems thats not the case 😅.

I don't get it. Literally every single screenshot is new. Take a look at how bad it looked before my change.

**Comment by shadmansaleh** [comment]
>I don't get it. Literally every single screenshot is new. Take a look at how bad it looked before my change.

So you took screenshot while section separators disabled?

**Comment by hoob3rt** [comment]
Yes, I don't know how that's hard to understand. The point of themes.md is to reflect different theme options not configuration options. There are screenshots of different configurations in readme.md.
