### ISSUE TITLE
Bug: Signify added displayed in black

### ISSUE THREAD

**Issue by shadmansaleh** [hoob3rt/lualine.nvim#107]
introduced in 3fecc953aafd9bded20f4797f4cca6287fff2068

The 'DiffAdd' group is for background highlighting it doesn't have a proper foreground property.
doing `hi DiffAdd` shpw only ctermbg and guibg properties . The default 'Diffchanged' & 'Diffdelete' are also background highlighter.

Funfact my colorscheme overrites them and makes the bg gray with foreground highlights . Colorchemes can make those colors look realy weird that's why I didn't want to extract colors from highlights :/

**Comment by hoob3rt** [comment]
True. Although most colorschemes define these colors our implementation does not handle it correctly. 
This should probably be something like
```
color = get_color(DiffAdd, fg) or get_color(DiffAdd, bg)
```
do you agree?

**Comment by shadmansaleh** [comment]
>
```lua
color = get_color(DiffAdd, fg) or get_color(DiffAdd, bg)
```

I donn't think get_color is returning nil if it was we would already be defaulting to default_colors provided inside signify component. Though I havesn't yet checked what it's returning. If `fg` doesn't return nil it wonn't work either.

**Comment by hoob3rt** [comment]
I know. Do you have a better solution though? We cannot possibly support all colorschemes. I think we should implement my suggestion and if that doesn't handle all edge cases then the user can configure colors themself

**Comment by shadmansaleh** [comment]
>I know. Do you have a better solution though? We cannot possibly support all colorschemes

I still think providing our defaults is better than trying to get colors from colorcheme when we have no idea what they look like . In one colorscheme I tested the signify components added and modified colors fg completely blended with bg so what I had was a big empty area and after that removed count.

We should just provide a set of colors if users donn't like it they can change it atlest the colors we provide wonn;t produce weird behiviors like this.
