### ISSUE TITLE
signify causes bad section highlights

### ISSUE THREAD

**Issue by hoob3rt** [hoob3rt/lualine.nvim#108]
setting signify compoent as the first component in section causes the padding to be in previous section's color. For some reason it only happens on on the left padding, not on the right. 

@shadmansaleh maybe you have an idea on why this happens

This also affects the diagnostics component which is not yet merged. 

~~Should be checked if applying any color to any component also replicates this.~~ 

Minimal config

```lua
lualine.sections.lualine_b = {'signify'}
```

![pic-window-210221-1739-14](https://user-images.githubusercontent.com/41551030/108631767-cd52a400-746b-11eb-9d28-6b69f41a2b48.png)

**Comment by shadmansaleh** [comment]
In signify and diagnostics we are returning with the highlights along with data from component ,while the padding is handled by padding global option on top of components return value .

**Comment by shadmansaleh** [comment]
In signify and diagnostics we are returning with the highlights along with data from component ,while the padding is handled by padding global option on top of components return value .

**Comment by shadmansaleh** [comment]
Checkout #109 it should resolve the issue
