### ISSUE TITLE
Doesn't work and no errors

### ISSUE THREAD

**Issue by suruaku** [hoob3rt/lualine.nvim#11]
I use NVIM v0.5.0-dev+916-gee5ece084
Installed lualine with Plug.
I have the following lines in my init.vim
```
lua << EOF
local lualine = require('lualine')
lualine.status()
EOF
```
I don't get any errors on startup but I don't see the bar either.
If I move lualine directory away from `~/.vim/plugged/` then I get an error that lualine is not found.

**Comment by hoob3rt** [comment]
Can you provide more info? Like your full config, installed plugins etc?
Lualine will probably not work if you have other statusline plugins installed like `airline` or `lightline` since they are very agressive in setting their own statuslines

**Comment by suruaku** [comment]
I use manjaro, tried to reinstall neovim-git (v0.5.0-dev+998-g48caf1df8) but that does not work either.
Here is my [nvim config](https://gitlab.com/suruaku/dotfiles/-/tree/master/config/nvim)
Having those lua lines in `init.vim` or `settings.vim`, doesn't work. I `PlugClean` airline so that's shouldn't be an issue.
With `:checkhealth` I don't get any issues.

**Comment by hoob3rt** [comment]
Please check if running running lua from command mode works. Try
```vim
:lua require('lualine').status()
```
or
```lua
:lua print(require('lualine').theme)
```

**Comment by hoob3rt** [comment]
I cannot replicate this issue with a minimal `vimrc`.
```vim
call plug#begin('~/.vim/plugged')
Plug 'hoob3rt/lualine.nvim'
call plug#end()
lua << EOF
local lualine = require('lualine')
lualine.status()
EOF
```

**Comment by suruaku** [comment]
> ```viml
> :lua require('lualine').status()
> ```
Doesn't do anything noticeable.
> 
> ```lua
> :lua print(require('lualine').theme)
> ```
Prints: gruvbox

It works with the minimal config you provided. I will take some time to check where is the issue.

**Comment by hoob3rt** [comment]
Well, this is an issue with your config then. Please review it and open a new issue if you find this bug is lualine related.
