### ISSUE TITLE
Discuss: Remove cterm colors from themes

### ISSUE THREAD

**Issue by shadmansaleh** [hoob3rt/lualine.nvim#110]
The genarated cterm values are pretty good . Most of the themes donn't have cterm values in them.  Those cterm values create unnecessary complexicity in themes . Also since rest of the codebase relies on genarated cterm colors (like section separators) They can look weird if themes provide cterm values thata re different . So I think we should remove cterm values from themes and relay solely on genarted cterm values .

**Comment by hoob3rt** [comment]
Yeah let's do it. A cleaner codebase is always better.
