### ISSUE TITLE
expose configuration through vimscript

### ISSUE THREAD

**Issue by hoob3rt** [hoob3rt/lualine.nvim#113]
User should be able to configure lualine with vimscript through global vim variables eg
```vim
let g:lualine_theme = 'nord'
```

similarly this should be supported in lua
```lua
vim.g.lualine_theme = 'nord'
```

**Comment by shadmansaleh** [comment]
Should be farely easy ro implement what options do you wana cover?

**Comment by hoob3rt** [comment]
> Should be farely easy ro implement what options do you wana cover?

I agree, should be really simple. I want the whole configuration to be available through vimscript. I'm not sure if we have to do `g:lualine_theme` maybe it's possible to do `g:lualine.theme`. I'm not sure I will have to look into vimscript more. 

There might be some issues with arrays. For now it's just an idea on what should be done next imo

**Comment by shadmansaleh** [comment]
>I want the whole configuration to be available through vimscript.

In whole configuration do you include sections like lualine.sections.lualine_a ?

**Comment by hoob3rt** [comment]
> > I want the whole configuration to be available through vimscript.
> 
> In whole configuration do you include sections like lualine.sections.lualine_a ?

I don't know what you mean

**Comment by shadmansaleh** [comment]
like we set which components to show in statusline by setting sections and inactive_sections right? I was asking if you want them to be configured through viml too ..

**Comment by hoob3rt** [comment]
Oh yeah. As I've said. Everything which is currently possible in lua should also be possible in native vimscript.
