### ISSUE TITLE
Bug: filetype component doesn't update the icon

### ISSUE THREAD

**Issue by darth** [hoob3rt/lualine.nvim#118]
Filetype component is stuck with the icon of the first file opened during the session.

As far as I can understand it is due to "caching" of the result of icon query:

```lua
if ok and not options.icon then
  local f_name,f_extension = vim.fn.expand('%:t'),vim.fn.expand('%:e')
  options.icon = devicons.get_icon(f_name,f_extension)
else
  ok = vim.fn.exists("*WebDevIconsGetFileTypeSymbol")
  if ok ~= 0 and not options.icon then
    options.icon = vim.fn.WebDevIconsGetFileTypeSymbol()
  end
end
```

I guess that such a caching was introduced to improve the performance. I think that correct implementation should save the filetype and the icon and update the icon when new filetype is different from the saved one. I can make a pull request if needed.

**Comment by shadmansaleh** [comment]
Thanks for reporting . Theirs no need to cache the icon . I'll fix it soon :)

**Comment by hoob3rt** [comment]
Nice catch, thanks for reporting that
