### ISSUE TITLE
`<CTRL_C>` breaks lualine

### ISSUE THREAD

**Issue by ihsanturk** [hoob3rt/lualine.nvim#122]
This is not happening every time I hit `CTRL_C` but sometimes.

![CTRL-C breaks lualine](http://g.recordit.co/W7BDFchcd2.gif)

The error is 
```
E5108: Error executing lua Keyboard interrupt
```

**Comment by hoob3rt** [comment]
Mmm, this looks like it's not an issue with lualine but with the lua nvim api. Can you confirm that `CTRL_C` also breaks other lua plugins?

**Comment by ihsanturk** [comment]
I haven't tried and don't know how to. Maybe secretly but this one was obvious.
Should I create the issue on https://github.com/neovim/neovim?

**Comment by shadmansaleh** [comment]
Can you provide more information of how to reproduce it ? It's proving to be really hard to reproduce . If we can find a easier way to reproduce it we can test it on other plugins ..

**Comment by ihsanturk** [comment]
I don't know how to reproduce exactly but I collected some key points I realised this issue occurs.

### 1. ✅ No Problem
1. Open `nvim`
2. Press `i` or `a`
3. Press `CTRL-C`
4. Go to step 2

### 2. ✅ No Problem
1. Open `nvim`
2. Press `i` or `a`
3. Type "hello"
3. Press `CTRL-C`
4. Go to step 2

### 3. ❌ Issue Occurs
1. Open an empty python file `nvim x.py`
2. Press `i` or `a`
3. Press `CTRL-C`
4. Press `i` or `a` one more time (sometimes more than twice)
5. Press `CTRL-C`
6. See the status line disappeared and error message printed.

So, I suspect that this is something to do with filetypes or Python specific. I tried other filetypes and saw they are affected too. Here the filetypes I tried

- ❌ Python
- ❌ C
- ❌ C++
- ❌ Rust

I also tested how many times should I go to insert mode and normal mode again to reproduce this issue. 
(I counted [`i`+`CTRL-C`] as 1)
- `nvim x.cc`: 5, 2, 3, 3, 4, 5, 2, 4, 7...

So, I couldn't see I pattern here.

---
### See Also
- [plugins I use](https://github.com/ihsanturk/dotfiles/blob/flakes/config/neovim/plugins.lua)
- [my lualine specific configuration](https://github.com/ihsanturk/dotfiles/blob/flakes/config/neovim/config/lualine.lua)

**Comment by shadmansaleh** [comment]
Thanks for the info. In your config I can see you are using separate function for relative paths . But  
lualines filename component provides relative path too . You can do 
```lua
lauline_c = {{'filename', full_path = true}},
```
You can checkout [Component options](https://github.com/hoob3rt/lualine.nvim#available-options) for details :)

**Comment by ihsanturk** [comment]
Thank you, but I also have the filename blocking mechanism for terminal buffers in that function.

**Comment by hoob3rt** [comment]
I stand by my point that it's not a lualine issue nor is it your configuration issue. All we are doing in our filetype components is calling `vim.fn.expand` functions. My guess is that it's a neovim/vim bug. Go ahead and submit an issue but I think you need to find a real cause of this crash as I suspect they would blame us if you refer a plugin with your ticket.

**Comment by shadmansaleh** [comment]
>I suspect they would blame us if you refer a plugin with your ticket.

Not true . The neovim guys are pretry cool . I had mentioned this issue on neovim [gitter](https://gitter.im/neovim/neovim) . This issue needs better way of reproduceing if the cause is ever to be found . After aton of attempts I was only able to make it happen twice . Also it just happens randomly . Trying aton of times the same thing and wating for a bug to affect is npt realistic to do . Also I was actualy gona ask @ihsanturk are you using current master of neovim? I'm using current master and this issue almost naver happens . If you're using an old version can you try current master maybe this has been partialy solved already :)

**Comment by ihsanturk** [comment]
I am using `v0.5.0-dev`. I will try `master`.
Thanks.

**Comment by ihsanturk** [comment]
I solved by mapping `<C-C>` -> `<C-[>` as a workaround.

**Comment by icholy** [comment]
I'm using nightly builds and this happens about once every hour for me. I cannot find a way to reliably reproduce.
