### ISSUE TITLE
Diff Colors do not reset

### ISSUE THREAD

**Issue by 1bharat** [hoob3rt/lualine.nvim#125]
I have this as my lualine sections
```
      lualine.sections = {
        lualine_a = { 'mode' },
        lualine_b = { 'branch' },
        lualine_c = { 'filename', 'diff', 'g:coc_status' },
        lualine_x = { 'encoding', 'fileformat', 'filetype' },
        lualine_y = { 'progress' },
        lualine_z = { 'location' },
      }

```

This is how it renders
![image](https://user-images.githubusercontent.com/6837979/110235085-45e45500-7f82-11eb-8760-eba5c4581d2e.png)

coc_status gets color of the diff.

**Comment by shadmansaleh** [comment]
@hoob3rt remove line (64-67) and (69-71)
And change this [line](https://github.com/hoob3rt/lualine.nvim/blob/332f488e2499d0f7a09276adcdd50995b348f7de/lua/lualine/utils/component.lua#L73) to 
```lua
separator = highlight_name .. (separator or '')
```
This should most likely fix this issue without causing any new . I can't create a pr now so see if it solves it .

**Comment by hoob3rt** [comment]
@1bharat thank you for reporting and @shadmansaleh thank you for providing a possible fix. I will take a look into it as soon as I can. It is probably also related to another bug I experienced a few days ago and started working on. Will link a pr when it's up

**Comment by hoob3rt** [comment]
This will probably take a while but I will try to setup proper tests in lualine through busted in #127. This bug annoys me as well so I might push a quickfix directly to master after I find the cause :smile:

**Comment by shadmansaleh** [comment]
@hoob3rt could you reproduce this one ? I thought it was because component separators were disabled . But I can't get it to occur on my device .

@1bharat can you provide your entire lualine config ?

**Comment by 1bharat** [comment]
```
  use {
    'hoob3rt/lualine.nvim',
    config = function()
      local lualine = require('lualine')
      lualine.options.theme = require('helpers').getLualineTheme()
      lualine.options.icons_enabled = false
      lualine.options.section_separators = nil
      lualine.options.component_separators = nil
      lualine.separator = '|'
      lualine.sections = {
        lualine_a = { 'mode' },
        lualine_b = { 'branch' },
        lualine_c = { 'filename', 'diff', 'g:coc_status' },
        lualine_x = { 'encoding', 'fileformat', 'filetype' },
        lualine_y = { 'progress' },
        lualine_z = { 'location' },
      }
      lualine.inactive_sections = {
        lualine_a = {  },
        lualine_b = { 'branch' },
        lualine_c = { 'filename' },
        lualine_x = {  },
        lualine_y = {  },
        lualine_z = { 'location' }
      }
      lualine.extensions = { 'fzf' }
      lualine.status()
    end
  }

```

**Comment by shadmansaleh** [comment]
@1bharat can you checkout if #128 fixes the issue for you ?

**Comment by 1bharat** [comment]
@shadmansaleh thanks. I checked out your commit and test it. It seems to have fixed it.

![image](https://user-images.githubusercontent.com/6837979/111019317-81fc3780-8412-11eb-9f21-ea1d4ac0983e.png)
