### ISSUE TITLE
Disabling section/component separator does not work.

### ISSUE THREAD

**Issue by 1bharat** [hoob3rt/lualine.nvim#134]
Current config
```
  use {
    'hoob3rt/lualine.nvim',
    requires = {'kyazdani42/nvim-web-devicons', opt = true},
    event = 'VimEnter *',
    config = function()
      require('lualine').setup{
        options = {
          theme = require('helpers').getLualineTheme(),
          icons_enabled = true,
          -- section_separators = nil, component_separators = nil
          component_separators = {'', ''},
          section_separators = {'', ''}
        },
        sections = {
          lualine_a = { 'mode' },
          lualine_b = { 'branch' },
          lualine_c = { 'filename', 'diff', 'g:coc_status' },
          lualine_x = { 'encoding', 'fileformat', 'filetype' },
          lualine_y = { 'progress' },
          lualine_z = { 'location' },
        },
        inactive_sections = {
          lualine_a = {  },
          lualine_b = { 'branch' },
          lualine_c = { 'filename' },
          lualine_x = {  },
          lualine_y = {  },
          lualine_z = { 'location' }
        },
        extensions = { 'fzf' }
      }
    end
  }
```

To disable separators, I tried using `section_separators = nil, component_separators = nil` which doesn't work. So I am currently setting empty values for them which works.

**Comment by shadmansaleh** [comment]
It's [here](https://github.com/hoob3rt/lualine.nvim/blob/21ea1acc619f95e3a4cf74be9341995ccf03c1ed/lua/lualine/init.lua#L14) . Since setting a key to nil removes the key from table , section/conponent_separator keys don't apear in pairs :D . @hoob3rt maybe we should just drop the nil to remove separators .

**Comment by 1bharat** [comment]
```
section_separators = '',
component_separators = ''
```
Yep this works too.

**Comment by hoob3rt** [comment]
> ```
> section_separators = '',
> component_separators = ''
> ```
> 
> Yep this works too. Thanks. We can close this issue then.

No, don't close this yet. I was aware of this and have a fix ready. I will merge it late today when I get on my private machine

**Comment by hoob3rt** [comment]
Actually seems like my solution was incorrect and @shadmansaleh is right about nil not being indexed. I have changed the docs in https://github.com/hoob3rt/lualine.nvim/commit/9db1a38357f8c3d240eef449f0ddd4e7656e253b
