### ISSUE TITLE
Suggestion: new component - hostname

### ISSUE THREAD

**Issue by konradmalik** [hoob3rt/lualine.nvim#135]
Hi, first of all thanks for a great plugin! :+1: 
I have a suggestion/feature request that I don't know how to implement myself (lua is a black magic for me right now) but it would be great if this plugin had a "hostname" component to display.
Much helpful when working with remote and local machines at the same time, as well as in dockerized environment.

**Comment by hoob3rt** [comment]
Yeah I like the idea. I will get it up tomorrow.

**Comment by shadmansaleh** [comment]
It's reaIly simple. I think best cource of action for this component will be vim.loop.get_hostname().

@konradmalik you can try putting

```lua
return vim.loop.get_hostname
```
in lua/lualine/components/hostname.lua file and you have yoir component :)

**Comment by konradmalik** [comment]
@hoob3rt thanks! below function works but an official component would probably be a better solution.
@shadmansaleh good call, however that function you mentioned does not seem to exists for me, this works instead:
```
lualine_c = {vim.loop.os_gethostname}
```

**Comment by shadmansaleh** [comment]
> however that function you mentioned does not seem to exists for me

Good catch, you're correct I typed it wrong . I just remembered there was something like that and typed . Sorry for not checking out first :)

**Comment by hoob3rt** [comment]
`hostname` component is now available in lualine https://github.com/hoob3rt/lualine.nvim/commit/c171d757979bfa59b04eebb45355fcdbfb90851e :smile:
