### ISSUE TITLE
Using custom lua functions: does function name need to be quoted, or not?

### ISSUE THREAD

**Issue by danngreen** [hoob3rt/lualine.nvim#137]
When I do this (copied from the README)

```
local function hello()
  return [[hello world]]
end

require('lualine').setup{
sections = {lualine_y = {'hello'}}
}
```
Section y will be empty. However, if I omit the quotes around `'hello'`, it works:
```
sections = {lualine_y = {hello}}
```

Is this just an error in the README? 
It's confusing, because this isn't what the README says to do, and it isn't how components are used ('filename', 'diagnostics', etc).

**Comment by hoob3rt** [comment]
Oh yeah, that's a recent error which came up in the readme. Functions should be without quotes.

**Comment by danngreen** [comment]
That's the answer I wanted to hear :)
...and BTW, great plugin, thanks!

**Comment by hoob3rt** [comment]
resolved with https://github.com/hoob3rt/lualine.nvim/commit/a105e96ddc1246c97e8905e7b7b2ddf694f1d895. Thanks for pointing that out :smile:
