### ISSUE TITLE
Diagnostic component colors not getting set correctly

### ISSUE THREAD

**Issue by timbedard** [hoob3rt/lualine.nvim#143]
It looks like the colors for the diagnostic component aren't getting set properly. I've tried it with just the theme colors and with setting the highlight groups manually before calling `setup()`.

What they are:
<img width="744" alt="Screen Shot 2021-03-25 at 12 47 10 AM" src="https://user-images.githubusercontent.com/1565211/112425219-b372de00-8d03-11eb-89ed-7ba82ae2df22.png">

What they should be (set manually through the `color_` options):
<img width="108" alt="Screen Shot 2021-03-25 at 12 56 56 AM" src="https://user-images.githubusercontent.com/1565211/112425989-1a44c700-8d05-11eb-9f4f-44c9c88a0405.png">

What the highlight groups for error and warn are:
<img width="140" alt="Screen Shot 2021-03-25 at 12 50 12 AM" src="https://user-images.githubusercontent.com/1565211/112425448-15cbde80-8d04-11eb-92bb-da2530fd1fa5.png">

Here's a minimal config:
```lua
require("packer").startup {
  function()
    use "wbthomason/packer.nvim"
    use {
      "gruvbox-community/gruvbox",
      config = function()
        vim.cmd("colorscheme gruvbox")
      end
    }
    use {
      "neovim/nvim-lspconfig",
      config = function()
        -- sumneko_lua setup, but you can substitute any lsp config here
      end
    }
    use {
      "hoob3rt/lualine.nvim",
      requires = "kyazdani42/nvim-web-devicons",
      config = function()
        require("lualine").setup {
          theme = "gruvbox",
          sections = {
            lualine_a = {"mode"},
            lualine_b = {"branch", "diff"},
            lualine_c = {"filename"},
            lualine_x = {
              {"diagnostics", sources = {"nvim_lsp"}},
              "encoding",
              "fileformat",
              "filetype"
            },
            lualine_y = {"progress"},
            lualine_z = {"location"}
          }
        }
      end
    }
  end
}
```

**Comment by shadmansaleh** [comment]
I don't think packer insures gruvbox will be loaded before lualine can you check if setting colorscheme to gruvbox before calling lualine setup resolve the issue ?

**Comment by hoob3rt** [comment]
@shadmansaleh is right. Packer is really weird about the code execution. This should probably be an issue in their repo unless it's done by design which is weird. I personally don't get any colors in both lualine's diagnostics/ diff or in [gitsigns.nvim](https://github.com/lewis6991/gitsigns.nvim) if I set a colorscheme in the packer file. 

The best solution I found is to set a colorscheme in `init.lua` / `init.vim` which kindda sucks as it breaks the coolness of packer having plugin's config in the same file.

**Comment by timbedard** [comment]
> I don't think packer ensures gruvbox will be loaded before lualine can you check if setting colorscheme to gruvbox before calling lualine setup resolve the issue ?

I didn't include it in the minimal config and should have, but I have tested it with the `after` feature of packer, which delays loading lualine until after gruvbox is loaded:
```lua
use {
  "hoob3rt/lualine.nvim",
  requires = "kyazdani42/nvim-web-devicons",
  after = "gruvbox",
  config = function()
    ...
  end
}
```

But I also just tried with manually using packadd and colorscheme like you suggested, and that doesn't work either.

**Comment by timbedard** [comment]
> @shadmansaleh is right. Packer is really weird about the code execution. This should probably be an issue in their repo go ahead and create it while linking this issue if I don't do it before you. I personally don't get any colors in both lualine's diagnostics/ diff or in [gitsigns.nvim](https://github.com/lewis6991/gitsigns.nvim) if I set a colorscheme in the packer file ( I used to have a config similar to yours)
> 
> The best workaround I found is to set a colorscheme in `init.lua` / `init.vim` which kindda sucks as it breaks the coolness of packer having plugin's config in the same file.

This also doesn't work for me.

**Comment by hoob3rt** [comment]
> > The best workaround I found is to set a colorscheme in `init.lua` / `init.vim` which kindda sucks as it breaks the coolness of packer having plugin's config in the same file.
> 
> This also doesn't work for me.

Okay, I will look more into it later then

**Comment by timbedard** [comment]
I dug around in the logic a bit already to no avail, but I'll give it another go tonight if I have time.

**Comment by timbedard** [comment]
Hoooooooooookay. Two things:
1. I ran a few of my tests with `-U` instead of `-u`. That's my bad. Some of my tests pulled in my basic config in `init.lua`, which include #2 below.
2. It looks like turning on `termguicolors` is what borks it. Unfortunately, disabling that also borks my colors.

**Comment by shadmansaleh** [comment]
> It looks like turning on termguicolors is what borks it

This makes absolutely no sence to me because we naver directly handle non termguicolors . Rather they are caculated in time of highlight genaration from termguicolors/rgb colors .So if non termguicolor works termguicoloe has to work.

By the way does your diff colors work correctly ?

**Comment by shadmansaleh** [comment]
I've found the issue lol. Should be quickfix :)

**Comment by shadmansaleh** [comment]
@timbedard see if #144 works.

**Comment by timbedard** [comment]
@shadmansaleh Nailed it!
