### ISSUE TITLE
Trouble applying option "color" to functional components

### ISSUE THREAD

**Issue by oncomouse** [hoob3rt/lualine.nvim#146]
I'm using a function to generate a component in the "z" section of my statusbar. I want to keep the mode-based background color but I want this component to have a normal font weight instead of bold. I configure it like this:

~~~lua
local function custom_location()
	return [[%l/%L:%c]]
end
require('lualine').setup{
	options = {},
	sections = {
		-- ...
		lualine_z = {
			{
				custom_location,
				color = {
				 	gui='none',
				},
				padding = 0,
				left_padding = 1,
				right_padding = 1,
			},
		},
		-- ...
	},
}
~~~

Using this configure, the reversed colorscheme is applied to the component (ie. in Normal mode, blue text and a black background, instead of black text on a blue background). Commenting out the color option, everything displays correctly. I think, looking through the code, this has something to do with how [get_transitional_highlight()](https://github.com/hoob3rt/lualine.nvim/blob/62c22d0f05c79a1bc890b15c1a1a5a0215936e2f/lua/lualine/highlight.lua#L154) is applied, but I'm not sure.

Thanks!

**Comment by shadmansaleh** [comment]
I'm sorry currently it's current not possible to apply color option to lua function component. You should wait for #141 get merged it will enable that . Or you could just use that branch until it's merged :)

**Comment by shadmansaleh** [comment]
@hoob3rt rhis is resolved with #141

**Comment by Ajith-stark** [comment]
Does this still works ?. Even that hack method is not working now.

**Comment by shadmansaleh** [comment]
Use [shadmansaleh/lualine.nvim](https://github.com/shadmansaleh/lualine.nvim)

[hoob3rt/lualine.nvim](https://github.com/hoob3rt/lualine.nvim) is currently not maintained . See https://github.com/hoob3rt/lualine.nvim/pull/311

You don't need the hack . function components accept options now.

**Comment by shadmansaleh** [comment]
`style` is not  a valid gui value . see `:h attr-list` for valid values.

**Comment by Ajith-stark** [comment]
I tried giving `bold`, `none` & `NONE` to `gui` prop  but there's no change in color .

**Comment by shadmansaleh** [comment]
You aren't applying color option to the component instead you've put color in the sections table .

It should be
```lua
lualine_b = {
      { spellstatus,
      color = {bg = '#8EC07C', fg= '#0A0A0A', gui='none'}, }
    },
```
