### ISSUE TITLE
Location is not correct if the line has UTF-8 characters

### ISSUE THREAD

**Issue by ronisbr** [hoob3rt/lualine.nvim#147]
Hi!

If the line has UTF-8 characters, then the location is not computed correctly:

<img width="690" alt="Captura de Tela 2021-03-27 às 20 25 59" src="https://user-images.githubusercontent.com/1068295/112737632-a5f36900-8f3a-11eb-8acc-930ea20600f9.png">

<img width="690" alt="Captura de Tela 2021-03-27 às 20 26 07" src="https://user-images.githubusercontent.com/1068295/112737635-aa1f8680-8f3a-11eb-9b10-741421d20cea.png">

**Comment by hoob3rt** [comment]
I can't replicate this using utf-8 characters on both my linux and osx systems. The location component uses built in location parsers. I doubt this will help but you can try updating your nvim to the newest version. Also, what terminal emulator are you using?

**Comment by ronisbr** [comment]
Hi @hoob3rt 

I rebuild neovim against `master` but the problem are still happening. I saw this problem with `ç` with iTerm and Alacritty.

**Comment by ronisbr** [comment]
Never mind, it is happening with stock Neovim configuration. Sorry for the noise.

**Comment by ronisbr** [comment]
BTW, this can be avoided using this component:

```
local function cursor_position()
  return tostring(vim.fn['line']("."))..":"..tostring(vim.fn['virtcol']("."))
end

require('lualine').setup{
  sections = {
    lualine_z = {cursor_position}
  }
}
```
