### ISSUE TITLE
file_status does not show readonly status of file

### ISSUE THREAD

**Issue by dimbleby** [hoob3rt/lualine.nvim#148]
The README says that filestatus "Displays file status (readonly status, modified status)".

But it doesn't show the readonly status, it [shows the modifiable status](https://github.com/hoob3rt/lualine.nvim/blob/62cdc8ec983eb189cfab7481f49e6bf058ff52ac/lua/lualine/components/filename.lua#L27). 

These aren't the same thing, if I have a read-only file - as in `chmod -w foo.txt` - then the buffer is considered modifiable but readonly.

IMO readonly would be a more useful thing to show, but anyway the README and the code ought to agree

**Comment by shadmansaleh** [comment]
You can tryout #149

**Comment by dimbleby** [comment]
that was quick!  yes, looks good to me, thanks

**Comment by shadmansaleh** [comment]
It was a one line :)
