### ISSUE TITLE
Support for lsp-status

### ISSUE THREAD

**Issue by andrewrynhard** [hoob3rt/lualine.nvim#150]
It would be nice to be able to pull diagnostics from [lsp-status](https://github.com/nvim-lua/lsp-status.nvim)

**Comment by andrewrynhard** [comment]
Looks like this is already possible:
```lua
function LspStatus()
   if #vim.lsp.buf_get_clients() < 1 then return "" end
   return lsp_status.status()
end
```
Then use `'LspStatus()'`:

```lua
...
lualine_c = {{'filename', file_status = true}, 'LspStatus()'},
...
```

**Comment by gbaranski** [comment]
@andrewrynhard Hi, have you managed to integrate lualine with lsp-status?

**Comment by andrewrynhard** [comment]
@gbaranski I have. Any part in particular you are interested in?

**Comment by gbaranski** [comment]
> @gbaranski I have. Any part in particular you are interested in?

Yeah, I'm looking for function where you show diagnostics in status bar.

**Comment by shadmansaleh** [comment]
> Yeah, I'm looking for function where you show diagnostics in status bar.

Can't the diagnostics component fill that role without lsp_status ?

**Comment by andrewrynhard** [comment]
@gbaranski 

```lua
local lualine = require('lualine')

function LspStatus()
    if #vim.lsp.buf_get_clients() < 1 then return "" end

    return lsp_status.status()
end

lualine.setup {
    options = {
        theme = "dracula",
        section_separators = {'', ''},
        component_separators = {'', ''},
        icons_enabled = true
    },
    sections = {
        lualine_a = {{'mode', upper = true}},
        lualine_b = {{'branch', icon = ''}, 'diff'},
        lualine_c = {{'filename', file_status = true, full_path = true}, 'LspStatus()'},
        lualine_x = {'encoding', 'fileformat', 'filetype'},
        lualine_y = {'progress'},
        lualine_z = {'location'}
    },
    inactive_sections = {
        lualine_a = {},
        lualine_b = {},
        lualine_c = {'filename'},
        lualine_x = {'location'},
        lualine_y = {},
        lualine_z = {}
    },
    extensions = {'fzf'}
}
```

Bit of a full example but notice
```lua
 lualine_c = {{'filename', file_status = true, full_path = true}, 'LspStatus()'},
```
The invocation of `LspStatus()` in particular. Just put that wherever you want it

![Screen Shot 2021-04-29 at 6 31 49 PM](https://user-images.githubusercontent.com/3383143/116637626-43b2cd00-a919-11eb-9886-b44bab5a23a1.png)

**Comment by shadmansaleh** [comment]
> The invocation of LspStatus() in particular. Just put that wherever you want it

@andrewrynhard  I think you should make LspStatus a local function and pass it to lualline . This is enough to add lspstatus :)

```lua
lualine_c = {
  {'filename', file_status = true, full_path = true},
  require'lsp_status'.status
},
```
but for readability you could do 
```lua
lsp_status = require'lsp_status'.status
require'lualine'.setup{
  ....
  lualine_c = {
    {'filename', file_status = true, full_path = true},
    lsp_status
  },
  ...
}
```

**Comment by gbaranski** [comment]
> > The invocation of LspStatus() in particular. Just put that wherever you want it
> 
> @andrewrynhard I think you should make LspStatus a local function and pass it to lualline . This is enough to add lspstatus :)
> 
> ```lua
> lualine_c = {
>   {'filename', file_status = true, full_path = true},
>   require'lsp_status'.status
> },
> ```
> 
> but for readability you could do
> 
> ```lua
> lsp_status = require'lsp_status'.status
> require'lualine'.setup{
>   ....
>   lualine_c = {
>     {'filename', file_status = true, full_path = true},
>     lsp_status
>   },
>   ...
> }
> ```

Works nice, thanks, do you maybe know what icon is it next to the tick which appears to me as white square? I've got nerd fonts installed.
![image](https://user-images.githubusercontent.com/34353640/116678237-5e348700-a9a9-11eb-81bf-762c9ba0f74f.png)

**Comment by gbaranski** [comment]
Ah okay nevermind, I've forgot to install noto-fonts-emoji, from what I see those emojis are quite buggy, sometimes it shows two ticks instead of one
![image](https://user-images.githubusercontent.com/34353640/116686708-7f4ea500-a9b4-11eb-9cb0-461e9e6e302f.png)

However after enabling command mode it dissapears.
