### ISSUE TITLE
Help file doc/lualine.txt, "Starting lualine" section seems to be incorrect

### ISSUE THREAD

**Issue by tlamarre91** [hoob3rt/lualine.nvim#158]
lualine.txt has this content:
```
STARTING LUALINE                                      *lualine_starting_lualine*
>
    local lualine = require('lualine')
    lualine.status()
<
```
If I'm not misunderstanding something (likely as I'm new to lua+neovim), shouldn't this be the same as the startup instructions in README.md: `require('lualine').setup{}`?

**Comment by shadmansaleh** [comment]
Yes, you're right. The setup in README is correct . Thanks for reporting :) . It seems vimdocs are out of sync. @hoobrt you forgot about vimdocs again 😆

**Comment by hoob3rt** [comment]
> Yes, you're right. The setup in README is correct . Thanks for reporting :) . It seems vimdocs are out of sync. @hoob3rt you forgot about vimdocs again 😆

yikes, you are right. I will update it properly today

**Comment by tlamarre91** [comment]
Thank you for taking a look, and for an cool plugin! Threw off the shackles of vim-airline today thanks to y'all.
