### ISSUE TITLE
fall back to powerline font icons?

### ISSUE THREAD

**Issue by coxackie** [hoob3rt/lualine.nvim#16]
Right now, if lualine does not detect devicons it offers only text. As a fallback, one could check whether powerline font "icons" are available (cascadia code, IBM plex, ...). Then, for example, a git branch icon can be `\ue0a0`. Not everyone want to have patched fonts installed.

**Comment by hoob3rt** [comment]
This is a really good idea.

**Comment by coxackie** [comment]
checking for powerline fonts though may not be as straightforward. What about creating a boolean setting, false by default, that could be set manually? Also, I am thinking that in the case where no devicons or PL fonts are available, some text may be nice; for example, "Git: " before the branch name.

**Comment by hoob3rt** [comment]
That's actually something I am planning on doing. Each component should probably have additional settings, like `icon`, `padding` etc. Please let me know if you have any other settings that come to your mind.

**Comment by coxackie** [comment]
As I mentioned in other comment, left and right separators would be nice. Furthermore, on the subject of this thread, when nerd fonts are used (which, as we said, can be triggered by an option), it would be nice to use additional symbols. For example, the line number and column number from [here](https://github.com/ryanoasis/powerline-extra-symbols#glyphs) to do this. Also, symbols like penguin (for unix/linux), etc., would be nice eye candy (although not strictly necessary).

**Comment by shadmansaleh** [comment]
Does this include filetype icons? Because I've no idea where am I gona get those?

**Comment by hoob3rt** [comment]
> Does this include filetype icons? Because I've no idea where am I gona get those?

There is no way we can support filetype icons without additional plugin installed.

**Comment by shadmansaleh** [comment]
>There is no way we can support filetype icons without additional plugin installed.

That's what I thought

**Comment by shadmansaleh** [comment]
Is the icon in branch component a poweline icon?

**Comment by coxackie** [comment]
> Is the icon in branch component a poweline icon?

I do not think so, but `nf-pl-branch` for https://www.nerdfonts.com/cheat-sheet is. Hex e0a0.

**Comment by hoob3rt** [comment]
>  Hex e0a0. 

Do you know how to use hex codes for icons in lua? 

> This could be used as a fallback. In fact, it most probably can be used also when dev fonts are there - I do not see any reason to have different icons.

Yea my idea is to use nerdfonts everywhere we can. Possibly only keep filetype icons to external plugin.

**Comment by coxackie** [comment]
> > Hex e0a0.
> 
> Do you know how to use hex codes for icons in lua?
> 
I just literally copy and paste the icon in a string. That is also what I do with the dev icons. I do not know whether this is the best way to do it... but it works.

**Comment by hoob3rt** [comment]
> > > Hex e0a0.
> > 
> > 
> > Do you know how to use hex codes for icons in lua?
> 
> I just literally copy and paste the icon in a string. That is also what I do with the dev icons. I do not know whether this is the best way to do it... but it works.

It does work but will be harder to maintain as there is no way of checking if copied icon is indeed a part of nerdfonts. Unfortunately it seems this is the only way to do it in lua so we will have to manage.

**Comment by shadmansaleh** [comment]
nf-dev-git looks  quite like curently used icon . Should that be used insted?
