### ISSUE TITLE
Automatic theme generation work incorrectly for zephyr-nvim

### ISSUE THREAD

**Issue by Shatur95** [hoob3rt/lualine.nvim#161]
Here is how it looks for [zephyr-nvim](https://github.com/glepnir/zephyr-nvim):
![изображение](https://user-images.githubusercontent.com/22453358/113788150-107b8480-9745-11eb-8218-56276fa1330f.png)

I also tested with [vim-code-dark](https://github.com/tomasiser/vim-code-dark) and it looks weird too.

Is this expected that automatic generation looks like this for some colorschemes?

**Comment by hoob3rt** [comment]
Yeah automatic does not work great on all themes... which is kind of expected since it's automatic and it's a guessing game. Not all vim colorschemes follow the same schema and I cannot think of a solution to make it better without coming up with a complicated algorithm (which would probably affect startup time by a lot)

**Comment by shadmansaleh** [comment]
@Shatur95  zephyr supports lightline you can run [lightline2lualineconverter](https://gist.github.com/shadmansaleh/000871c9a608a012721c6acc6d7a19b9) and make a pr to add the theme to lightline . It's really easy to do :)

**Comment by Shatur95** [comment]
> Edit: zephyr doesn't support lightline/airline :O . The link on the issue was to vim-code-dark . And I went there and didn't check the name lol .

Sorry, typo :)

> I just looked at the previous pr for codedark and it's from you who am I telling :P

Yes, I already sent a colorscheme for vim-code-dark,  just decided to clarify if current `auto` behavior is okay :)
At the moment, the feature never worked correctly for me for themes I tried (I've also tried other threads before, but can't remember their names).

**Comment by shadmansaleh** [comment]
> At the moment, the feature never worked correctly for me for themes I tried (I've also tried other threads before, but can't remember their names).

@Shatur95  How do you define if it worked correctly or not ? Knowing this might help make it better.

**Comment by Shatur95** [comment]
> @Shatur95 How do you define if it worked correctly or not ? Knowing this might help make it better.

Colors are not suitable. It just looks very weird, like in my first screenshot (gray color even not present in zephyr theme).

**Comment by shadmansaleh** [comment]
Humm . lualine_c section probably should be close to Normal . We are curently trusting StatusLine hightlight group to be something close . Though in this case It's wildly different . 

Maybe try changing StatusLine -> Normal [here](https://github.com/hoob3rt/lualine.nvim/blob/37dfbe787c615fd892e80732a87f16a690de1283/lua/lualine/themes/auto.lua#L114) And see if it improves colors for zephyr and other colorscheme :)

**Comment by Shatur95** [comment]
> Nope we probably should just swap back1 and back2

Looks much better, but probably gray color should be removed from here:

![изображение](https://user-images.githubusercontent.com/22453358/113826310-adacdc00-978a-11eb-9440-e05825860a39.png)

Probably I can adjust this highlighting group manually in my config?

**Comment by Shatur95** [comment]
Checked other themes - yes, it `back2` should also be `Normal`.

**Comment by shadmansaleh** [comment]
You can 
```lua
local my_theme = require'lualine.themes.auto'

theme.normal.c.bg = "#223344"

retquire'lualine'.setup{
  options = {
    theme = my_theme,
  }
 ...
}
```

**Comment by Shatur95** [comment]
> You can change the highlight group . If you don't want to do that you can also tweek lualine themes as part of lualine config like following .

Thank you! Is there a way to extract a value from theme to avoid hardcoding color?

**Comment by shadmansaleh** [comment]
my_theme.normal.c.bg already has it's value

You could do something like
```lua
my_theme.normal.b.bg, my_theme.normal.c.bg = mytheme.normal.c.bg, my_theme.b.bg
```
to swap theme . Though you will probably have to swap other mode too

**Comment by Shatur95** [comment]
> You can change the highlight group . If you don't want to do that you can also tweek lualine themes as part of lualine config like following .

Got it, make it look nice using the following code:

```lua
local my_theme = require('lualine.themes.auto')
my_theme.normal.c.bg = my_theme.normal.b.bg
my_theme.insert.c.bg = my_theme.insert.b.bg
my_theme.replace.c.bg = my_theme.replace.b.bg
my_theme.visual.c.bg = my_theme.visual.b.bg
my_theme.command.c.bg = my_theme.command.b.bg
```

**Comment by shadmansaleh** [comment]
I had unintentionaly broke it yesterday ;( . #162 should fix it once merged . Sorry
