### ISSUE TITLE
Custom theme config is not loading anymore

### ISSUE THREAD

**Issue by 1bharat** [hoob3rt/lualine.nvim#163]
I used to load a custom lualine theme that is not in the themes list as below

```
      require('lualine').setup{
        options = {
          theme = require('helpers').getLualineTheme(),
          icons_enabled = true,
          component_separators = '',
          section_separators = ''
        },
        sections = {
         ...
```
`getLualineTheme` returns the same object as in any of the themes. With the recent change, it has stopped working. 
An error is thrown at this line https://github.com/hoob3rt/lualine.nvim/blob/master/lua/lualine/highlight.lua#L32. 
The error is as follow
```
Error in packer_compiled: ...vim/site/pack/packer/opt/packer.nvim/lua/packer/load.lua:43: ...e/pac...opt/lualine.nvim/lua/lualine/highlight.lua:32: bad argument #1 to 'pairs' (table expected, got nil)
```

**Comment by shadmansaleh** [comment]
related to #162
