### ISSUE TITLE
Error executing update_status

### ISSUE THREAD

**Issue by konradmalik** [hoob3rt/lualine.nvim#169]
Hey,
not sure why but after a recent pull I get this error (twice) everytime I load this plugin:
```
E5108: Error executing lua ...pack/packer/start/lualine.nvim/lua/lualine/component.lua:121: attempt to call method 'update_status' (a string value)
```
Any ideas?

**Comment by shadmansaleh** [comment]
Please provide your config.

**Comment by shadmansaleh** [comment]
@konradmalik can you confirm if #170 fixes the issue ?

**Comment by konradmalik** [comment]
Yes, indeed with this PR it seems fixed ;)

**Comment by shadmansaleh** [comment]
> Yes, indeed with this PR it seems fixed ;)

Cool then update. It's been merged :)
