### ISSUE TITLE
Bug: Vim Function Component Showing Nil

### ISSUE THREAD

**Issue by jebaum** [hoob3rt/lualine.nvim#176]
### Self Checks

- [X] I'm using the latest lualine and neovim nightly.
- [x] I didn't find the issue in exsisting issues or prs.

### How to reproduce the problem
Neovim version: NVIM v0.5.0-dev+1248-g6b16ec701
lualine version: aa844a9
lualine config:

```vim
function! StatuslineTabWarning()
    let tabs = search('^\t', 'nw') != 0
    let spaces = search('^ ', 'nw') != 0

    if tabs && spaces
        return '[mixed-indenting]'
    elseif (spaces && !&et) || (tabs && &et) " expandtab setting doesn't match buffer contents
        return '[&et]'
    endif
    return ''
endfunction

function! StatuslineTrailingSpaceWarning()
    if search('\s\+$', 'nw') != 0
        return '[\s]'
    endif
    return ''
endfunction

let g:lualine = {
    \'options' : {
    \  'theme' : 'onedark',
    \  'section_separators' : ['', ''],
    \  'component_separators' : ['', ''],
    \},
    \'sections' : {
    \  'lualine_b' : [ ['branch', {'icon': '',}, ], 'diff' ],
    \  'lualine_c' : [ ['filename', {'full_path': v:true,}, ] ],
    \  'lualine_z' : [ ['StatuslineTabWarning', {'color': {'fg': '#ffffff', 'bg': '#ff0000'} }], 'StatuslineTrailingSpaceWarning', 'location' ],
    \},
    \'inactive_sections' : {
    \  'lualine_c' : [ ['filename', {'full_path': v:true } ] ],
    \}
\}
lua require('lualine').setup{}
```

### Actual behaviour
The two function components show up as the literal text `nil` no matter what

### Expected behaviour
The two function components should show some text if there are trailing spaces or mixed indentation in the buffer, and disappear if not.

### Aditional information
This worked correctly up until recently. A quick bisect shows that https://github.com/hoob3rt/lualine.nvim/commit/77c4c4748254cd6087c6cc1e8be72485d278eb48 introduced the issue. I don't know any lua so can't debug further than that unfortunately. Seems like it could be related to https://github.com/hoob3rt/lualine.nvim/commit/aa844a955504c6f5fda3f7fe4e15c3d215b5b8c3 though

### Minimal config to reproduce the issue
Provided above

<details>
<summary>Config</summary>

</details>

**Comment by shadmansaleh** [comment]
Thanks for reporting and for taking the time to bisect :) . Can you check if #177 fixes the issue for you ?

**Comment by jebaum** [comment]
Yep, checking that out locally fixes the issue.

Thanks!!

**Comment by shadmansaleh** [comment]
I've merged it . it should be fixed in master.

> I don't know any lua so can't debug further than that unfortunately.

If you don't mind i'd suggest you take a look at lua it's alot better then viml

These are great resources to get started .
- [learn X in Y minutes](https://learnxinyminutes.com/docs/lua/)
- [nanotees neovim lua guide](https://github.com/nanotee/nvim-lua-guide)

lua is a really tiny language you'll be done with them in an hour or so :)
