### ISSUE TITLE
Refactor: Decouple section separator from sections

### ISSUE THREAD

**Issue by shadmansaleh** [hoob3rt/lualine.nvim#179]
### Requested feature

Allow transitional separators at component label instead of section label . While keeping current functionality intact

### Motivation

I want to separate the section separators we have now from sections and handle them at component label . The statusline function in init.lua is too complicated it is in dire need of a refractor IMO . Also allowing highlighted transitional separators will help with custom statusline a lot. And we can create cooler looks with color option. But I'm out of idea on how to do it without overcomplicating things . If anyone has an idea please share here .

**Comment by hoob3rt** [comment]
I agree the statusline function is over the top for what it does. Please provide more information about your seprator idea. I don't quite get what you want to achieve here.

**Comment by shadmansaleh** [comment]
> Please provide more information about your seprator idea.

I want to give components a global option to set left & right transitional separator . This'll be particularly useful for component that use different color in a section then the theme (Like with color option) . The evilline didn't have transitional separators if it did it would have been pretty unintuitional and complicated to handle.
