### ISSUE TITLE
Bug: Unable to start lualine

### ISSUE THREAD

**Issue by ssoriche** [hoob3rt/lualine.nvim#180]
### Self Checks

- [x] I'm using the latest lualine and neovim nightly.
- [X] I didn't find the issue in exsisting issues or prs.

### How to reproduce the problem

Start neovim after updating the following error message is encountered:

```
E15: Invalid expression: v:lua.require'lualine'.statusline()
```

### Actual behaviour

lualine does not start.

### Expected behaviour

lualine starts without an error.

### Aditional information

Reverting to commit 0018643 starts lualine without the error message. Every commit after that starts with the error.

### Minimal config to reproduce the issue

<details>
<summary>Config</summary>

```
local lualine = require('lualine').setup {}
```

</details>

**Comment by shadmansaleh** [comment]
> I'm using the latest lualine and neovim nightly.

I'm sure that's not the case ☹️. Update to latest nightly / neovim master and it the problem persists please let me know 🙂

**Comment by hoob3rt** [comment]
just to be sure please provide output of `nvim --version`

**Comment by strboul** [comment]
I'm having the same issue
```
NVIM v0.5.0-dev+1115-gc1fbc2ddf
```

**Comment by hoob3rt** [comment]
I just updated neovim on both my linux and macos machines and cannot reproduce this error
```
NVIM v0.5.0-dev+1260-ga6504ec33
```

**Comment by shadmansaleh** [comment]
> NVIM v0.5.0-dev+1115-gc1fbc2ddf

That build is from 26, Feb please upgrade to latest nightly

**Comment by strboul** [comment]
Upgraded to the `NVIM v0.5.0-dev+1259-gfe808f02f` and it works perfectly :+1:

**Comment by ssoriche** [comment]
Last night `brew` told me my `neovim --head` was up to date. Today it tells me there's a new version. With this new version the issue is no longer occurs.
