### ISSUE TITLE
Bug: docs/tags conflict

### ISSUE THREAD

**Issue by theroncross** [hoob3rt/lualine.nvim#183]
### Self Checks

- [ ] I'm using the latest lualine and neovim nightly.
- [x] I didn't find the issue in exsisting issues or prs.

### How to reproduce the problem
:PlugUpdate from `2b32fb0..2158095`
### Actual behaviour
PlugUpdate output 
```
 x lualine.nvim:
     error: Your local changes to the following files would be overwritten by merge:
       doc/tags
     Please commit your changes or stash them before you merge.
     Aborting
     Updating 2b32fb0..2158095
```
### Expected behaviour
Successful update

### Aditional information
NVIM v0.5.0-dev+1231-g48e805728

### Minimal config to reproduce the issue

<details>
<summary>Config</summary>

</details>

**Comment by shadmansaleh** [comment]
i'm not really sure . But some how your clone is modified . We had A tag missing in help files .Though it was fixed anout an week ago it's possible that helptags ran when your repo was at that state . Can you goto the folder the repo is cloned at ad run the following command?
```
git reset --hard
```
Then update . That should fix your repo . Else reinstalling will fix it too :)
