### ISSUE TITLE
Feat: Result Search Count

### ISSUE THREAD

**Issue by wlacruzpy** [hoob3rt/lualine.nvim#186]
### Requested feature

I tried to count my result search, but it is not possible or i don't know how to make it work

### Motivation

Is way useful to count some kind of occurrence of a thing xD

**Comment by hoob3rt** [comment]
I personally don't see a reason to have it in the statusline. For me the search count is already available below. 
![Screenshot 2021-04-20 at 15 12 58](https://user-images.githubusercontent.com/41551030/115401651-e9b05a00-a1ea-11eb-9eba-f7052e76681e.png)

**Comment by shadmansaleh** [comment]
Wait for https://github.com/neovim/neovim/pull/14406 to get merged in core . Then you'll be able to make your component easily. There's even an example in docs :D

**Comment by vxio** [comment]
In case @wlacruzpy or anyone comes across this request:
You can write a custom function like 
```lua
function search_cnt()
  local res = fn.searchcount()
  
  if res.total > 0 then
    return string.format("%s/%d %s", res.current, res.total, fn.getreg('/'))
   else 
     return ""
  end
end

require('lualine').setup({
 options = {theme = 'auto'},
 sections = {
   lualine_a = {'mode', search_cnt},
 }
})
```

which'll render <img width="398" alt="CleanShot 2021-11-14 at 15 46 28@2x" src="https://user-images.githubusercontent.com/29054071/141703743-9d34116d-ad7d-4f14-a0ec-7d8d2fca5a4a.png">

**Comment by Mo8it** [comment]
@vxio @mario-amazing  Thanks for your snippets!

My modifications:
- Add "S" to `vim.o.shortmess` to disable showing the default match count showed on the lower right side (see `:h shortmess`).
- Add `local` to the function.
- Add a check of `v:hlsearch` with `vim.api.nvim_get_vvar("hlsearch")`. This means that the match count disappears if you run `:noh`.
- Use `%d` instead of `%s` for formating `res.current` which is a decimal.
- Remove `vim.fn.getreg("/")` because I can see the search term below the count anyway (opinionated).
- Add `type = "lua_expr"` to be more explicit (otherwise lualine would try to guess according to the documentation).


```
vim.o.shortmess = vim.o.shortmess .. "S"

local function search_count()
	if vim.api.nvim_get_vvar("hlsearch") == 1 then
		local res = vim.fn.searchcount()

		if res.total > 0 then
			return string.format("%d/%d", res.current, res.total)
		end
	end

	return ""
end

require("lualine").setup({
	sections = {
		lualine_b = { { search_count, type = "lua_expr" } },
	},
})
```

**Comment by idr4n** [comment]
Would it be possible to start showing the search count while typing the search term? Search count only shows once I hit Enter. There is a similar function script in Vim that does this, but I wouldn't know how to implement it in Lua properly.

**Comment by hughfenghen** [comment]
When scrolling in nvim, hlsearch might get canceled out; hence I added an event to re-enable it.

```lua
  vim.api.nvim_create_autocmd("WinScrolled", {
    callback = function()
      if vim.fn.getreg "/" ~= "" and vim.v.hlsearch == 0 then vim.opt.hlsearch = true end
    end,
  })

  local function search_cnt()
    if vim.v.hlsearch == 0 then return "" end

    local _, res = pcall(vim.fn.searchcount, { maxcount = 999, timeout = 1000 })

    if res.total > 0 then return string.format("🔍[%d/%d]", res.current, res.total) end

    return "🔍[?/?]"
  end

```
