### ISSUE TITLE
Bug: Cannot configure theme usage, Lualine always use gruvbox

### ISSUE THREAD

**Issue by noomly** [hoob3rt/lualine.nvim#190]
### Self Checks

- [X] I'm using the latest lualine and neovim nightly.
- [X] I didn't find the issue in exsisting issues or prs.

### How to reproduce the problem

Enable the plugin, configure the plugin to use another colorscheme via:

```lua
require('lualine').setup{
    theme = "dracula",
}
``` 

### Actual behaviour

Lualine uses gruvbox colorscheme.

### Expected behaviour

Lualine uses dracula colorscheme.

### Minimal config to reproduce the issue

```vimscript
call plug#begin("~/.local/share/nvim/plugged")

Plug 'hoob3rt/lualine.nvim'
Plug 'kyazdani42/nvim-web-devicons'

Plug 'dracula/vim'

call plug#end()

lua <<EOF
vim.cmd("colorscheme dracula")

require("lualine").setup{
    theme = "dracula",
}
EOF

set termguicolors
set background=dark

syntax enable

filetype on
filetype plugin on
filetype indent on

```

**Comment by shadmansaleh** [comment]
You're suppose to do
```lua
require('lualine').setup{
    options = {
        theme = "dracula",
    }
}
```

look [here](https://github.com/hoob3rt/lualine.nvim#setting-a-theme)
