### ISSUE TITLE
Bug: cannot initialize lualine: `E15: Invalid expression: v:require'lualine'.statusline()`

### ISSUE THREAD

**Issue by swanysimon** [hoob3rt/lualine.nvim#195]
I just updated my lualine plugin (which is a git submodule in <neovim_home>/pack/third_party/start/lualine) and no longer have a pretty statusline.

```
$ nvim --version
NVIM v0.5.0-dev+a7d9df9
Build type: Release
LuaJIT 2.1.0-beta3
```

Lualine version:

```
$ git --no-pager log -1
commit e3a558bc1dfbda29cde5b356b975a8abaf3f41b2 (HEAD -> master, origin/master, origin/HEAD)
Author: Shadman <shadmansaleh3@gmail.com>
Date:   Fri Apr 23 17:41:41 2021 +0600

    Fix component separator not removed for string color (#192)
```

On the latest MacOS.

### Self Checks

- [x] I'm using the latest lualine and neovim nightly.
- [x] I didn't find the issue in exsisting issues or prs.

### How to reproduce the problem

In my `init.lua`:

```
lua require('lualine').setup {}
```

### Actual behaviour

Launch neovim and see the error: <img width="1030" alt="Screen Shot 2021-04-25 at 13 45 18" src="https://user-images.githubusercontent.com/3290271/116009463-be54b300-a5ce-11eb-9285-0563b4369562.png">

### Expected behaviour

The status line is set without an error.

### Aditional information

At a glance (and with very little Lua knowledge or how this plugin really works) 287e5def31773f12f0f70bb2dcbdc9622e51b3ea looks suspicious.

### Minimal config to reproduce the issue

Described in the steps to reproduce.

**Comment by ibraheemdev** [comment]
I have the same issue.

**Comment by hoob3rt** [comment]
This does not happen on my linux machine, I will see how macos behaves in 9 hours. Did you update neovim in the past 3 days? I didn't have any issues on friday

**Comment by ibraheemdev** [comment]
I'm on Linux with neovim v0.5.0-dev+1155-g054eb31dc, I haven't updated recently.

**Comment by hoob3rt** [comment]
> I'm on Linux with neovim v0.5.0-dev+1155-g054eb31dc.

https://github.com/hoob3rt/lualine.nvim/issues/180#issuecomment-821111217

Well then clearly you are not on the newest version, I recommend updating your neovim

**Comment by swanysimon** [comment]
I put my neovim version in the issue when I created it. This was after running `brew upgrade` because I realized you may be relying on the latest version. Even as I try to upgrade this morning, there are no neovim changes to upgrade to.

You're totally right this might be a MacOS issue.

**Comment by hoob3rt** [comment]
I am running MacOS on my work computer and have no issues at all. Did you install neovim using 
`brew install --build-from-source --HEAD neovim`?

**Comment by swanysimon** [comment]
Ah I'm really sorry about the delay. I don't know what I did, but the day after I posted that message things were working again. Unclear if brew updated or what, but things are working now.

Cheers,
Simon
