### ISSUE TITLE
Feat: Execute vim method

### ISSUE THREAD

**Issue by Mte90** [hoob3rt/lualine.nvim#199]
### Requested feature
Integrate this on this statusline: https://github.com/mte90/vim-no-fixme/tree/patch-1

### Motivation
I have that fork because has an improved detection of TODO/FIXME comments compared to the original.
As today I execute the function in lightline `nofixme#amount` to print this.

Basically I don't know if it is possible to run a vim command or otherwise rewrite (or integrate that feature) in this plugin.

The plugin seems fantastic and does everything I need with removal of few plugins and this is the only thing that I cannot keep right now.

**Comment by shadmansaleh** [comment]
It's already possible read the [docs](https://github.com/hoob3rt/lualine.nvim#changing-components-in-lualine-sections) using vim functions are documented

**Comment by Mte90** [comment]
Dammit I missed it -.-'
