### ISSUE TITLE
Feat: ALE support

### ISSUE THREAD

**Issue by Mte90** [hoob3rt/lualine.nvim#200]
### Requested feature
For lightline there is https://github.com/maximbaz/lightline-ale

### Motivation
In this way it is easy to move on Lua also if there isn't yet a full alternative to ALE in lua.

**Comment by shadmansaleh** [comment]
Already suppoerted again read the [docs](https://github.com/hoob3rt/lualine.nvim#component-specific-options) Check the diagnostics component.

**Comment by shadmansaleh** [comment]
You can actually use that plugin too . It'll actually use that plugin in lualine too . I beleave same way vim functionc can be used as said in your previous issue. If you think there's more that needs to be supported please reopen the issue and that can be disscused . 

Sorry for directly closing issue . But opening an issue for a fea/ture request with even checking if it's already there is a realy poor effort :/

**Comment by Mte90** [comment]
I checked the readme, I didn't saw ALE in the plugin list so I opened the request. I didn't know that the diagnostic component support ALE.

**Comment by shadmansaleh** [comment]
> I checked the readme, I didn't saw ALE in the plugin list so I opened the request.

No problem it can happen . I'll still recomend reading the entire thing :)  . 

Sorry for being like that earlier . I was rather annoyed by something else back then :P .

Lualine should be able to replace all use cases of lightline as far as I know.
