### ISSUE TITLE
Feat: Disable on custom buffer

### ISSUE THREAD

**Issue by Mte90** [hoob3rt/lualine.nvim#202]
### Requested feature
I checked in the docs and there isn't a way to say that on 'startify' buffer to not print the status line like for chadtree as example.

### Motivation
In this way I can disable in symbols-outline and in startify.

**Comment by shadmansaleh** [comment]
Do you wan;t to disable entire statusline or just some component ?

**Comment by Mte90** [comment]
```
local exclude_statusline = function()
    local fts = {'startify', 'Outline'}
    for _, ft in pairs(fts) do
        if (vim.bo.filetype == ft) then return false end
    end
    return true
end

require('lualine').setup{
    options = {
        theme = 'papercolor_light',
        icons_enabled = true,
        condition = exclude_statusline
```

I used your code and works :-)
Usually status line have a parameter where you define the list of those to exclude.
