### ISSUE TITLE
Feat: reload colors

### ISSUE THREAD

**Issue by Shatur95** [hoob3rt/lualine.nvim#207]
### Requested feature
I would like to have the ability to reload colors on theme.

### Motivation
Some color schemes support multiple color options. For example, [tokyonight](https://github.com/folke/tokyonight.nvim). When the theme is reloaded, the colors in the lualine remain the same.

Of course, you can create a separate color theme for each option and apply them when loading, but they will have exactly the same code. [Example](https://github.com/folke/tokyonight.nvim/blob/main/lua/lualine/themes/tokyonight.lua).

### Suggestion
The simplest solution is to allow functions to be defined in themes that can be called manually from theme to regenerate colors. Currently, if I define a custom function in any color scheme, I get the following error:

```
E5113: Error while calling lua chunk: .../pack/plugins/opt/lualine.nvim/lua/lualine/highlight.lua:41: bad argument #1 to 'pairs' (tabl
e expected, got function)
```

Can we check if the value is a string?

**Comment by shadmansaleh** [comment]
We actually had it #130 :P

**Comment by Shatur95** [comment]
Interesting. Would be nice to put it back :D

**Comment by shadmansaleh** [comment]
>Interesting. Would be nice to put it back :D

You'll have to convince @hoob3rt

**Comment by hoob3rt** [comment]
While I agree that having this option is nice I don't like it as it introduces inconsistency with all other options. If we allow theme changes then we should also allow other options to change at runtime. 

We didn't have that at the time of #130 and I decided it would be better to have a simpler codebase instead of a feature which in my opinion is only useful when playing around in colorschemes/config. And if you are playing around with colorschemes/config then it's easier imo to change it in your config than doing something like `:lua require'lualine'.options.theme = 'something'`.

**Comment by shadmansaleh** [comment]
> lua require'lualine'.options.theme = 'something'

That's not something you can do ....
configs were moved out of main lualine file .

**Comment by Shatur95** [comment]
@hoob3rt, You probably misunderstood me. I didn't mean to introduce the feature to change theme at runtime. I meant to be able to reload its colors, because they may change depending on the Neovim `background` option.

**Comment by hoob3rt** [comment]
> > lua require'lualine'.options.theme = 'something'
> 
> That's not something you can do ....
> configs were moved out of main lualine file .

I am well aware of that, I moved them myself, this was just an example of how it could work

>@hoob3rt, You probably misunderstood me. I didn't mean to introduce the feature to change theme at runtime. I meant to be able to reload its colors, because they may change depending on the Neovim background option.

I personally don't see a reason to change a colorscheme/background color in one vim session. If you use that feature yourself then go ahead and submit a pr

**Comment by Shatur95** [comment]
> If you use that feature yourself then go ahead and submit a pr

I'm not sure if you will like this change. At the moment, lualine colors are cached and reapplied when the colorscheme is changed. We could reload the whole lualine theme, but this makes little sense, since all presented themes are just dictionaries with colors.
In [my theme](https://github.com/Shatur95/neovim-ayu/blob/master/lua/lualine/themes/ayu.lua), this dictionary generated depending on the `background` option. Maybe it would be nice to have some API for such "dynamic" themes?

**Comment by Shatur95** [comment]
@hoob3rt, I think a have an idea. What if allow to specify highlighting group names in theme? Colors will be linked to such groups and automatically reloaded when theme is changed.
This is how galaxyline works. Colors can be specified via array or via group name.

**Comment by Shatur95** [comment]
Oh, it is already possible. Awesome.

**Comment by Hubro** [comment]
> I personally don't see a reason to change a colorscheme/background color in one vim session

Automatically switching between light and dark color schemes to match the operating system global theme.
