### ISSUE TITLE
[suggestion] Implement optional powerline aesthetic with < and > characters

### ISSUE THREAD

**Issue by Monklite** [hoob3rt/lualine.nvim#21]
In other status bars such as airline or lightline, there are options to implement powerline-like aesthetics like [this](https://i.redd.it/a2hrqr8ocbl31.png) using < and > keys. I would love to see this added, shouldn't be too difficult

**Comment by coxackie** [comment]
I think this could be partly done by allowing to specify different left and right separators. One could then use glyphs from [here](https://github.com/ryanoasis/powerline-extra-symbols#glyphs) to do this.
