### ISSUE TITLE
Bug: tabline shows only one file

### ISSUE THREAD

**Issue by Mte90** [hoob3rt/lualine.nvim#211]
### Self Checks

- [x] I'm using the latest lualine and neovim nightly.
- [x] I didn't find the issue in exsisting issues or prs.

### How to reproduce the problem

Enable tabline.

### Actual behaviour
Open a file with chadtree in a new tab or with tabedit but the tabline has only one single file.

### Expected behaviour

Show tabs for the various file opened.

**Comment by hoob3rt** [comment]
This is not a bug. The tabline option only refers to putting your statusline on top. This was further discussed [here](https://github.com/hoob3rt/lualine.nvim/pull/92#issuecomment-791163067)

**Comment by Mte90** [comment]
In the readme it wasn't explained and the previous statusline plugin I was using was doing also that.
Sorry for the confusion.

**Comment by shadmansaleh** [comment]
shadmansaleh#42 has been merged now [shadmansaleh/lualine.nvim](https://github.com/shadmansaleh/lualine.nvim) has traditional tabline / bufferline support.

See #311 to know what else has changed in the fork.
