### ISSUE TITLE
Add shortened path to filename in evil line?

### ISSUE THREAD

**Issue by shaunsingh** [hoob3rt/lualine.nvim#218]
Hi, thank you for the awesome plugin! Is it possible to add a shortened path in front of the filename, similar to the one done in doom-modeline?

For example: 

<img width="618" alt="image" src="https://user-images.githubusercontent.com/71196912/117559629-df98b300-b054-11eb-9008-16b2f75f0248.png">

If it's outside the scope of the example, could you kindly suggest how I could implement it in my own config. Thank you once again

**Comment by shadmansaleh** [comment]
evilline was actually a config example you're suppose to adapt it as your need . The filename component is configured [here](https://gist.github.com/shadmansaleh/cd526bc166237a5cbd51429cc1f6291b#file-evil_lualine-lua-L143) .

If you see the options section in [readme](https://github.com/hoob3rt/lualine.nvim#component-specific-options) you can see all the options available . Also keep an eye out for #201 it'll change some of that behavior . I'd suggest you read the README or the docs in neovim `:h lualine` . There you'll find how to configure lualine :)
