### ISSUE TITLE
Bug: filetype configuration warning

### ISSUE THREAD

**Issue by ronniedroid** [hoob3rt/lualine.nvim#235]
neovim sends an error message `filetype component configuration changed, see :h lualine_custom_options`

- [x] I'm using the latest lualine and neovim nightly.
- [x] I didn't find the issue in exsisting issues or prs.

### How to reproduce the problem
update your lualine though your package manager

<details>
<summary>Config</summary>

require("lualine").setup {
  options = {
    theme = "modus_vivendi",
    section_separators = {"", ""},
    component_separators = {"", ""},
    disabled_filetypes = {},
    icons_enabled = true,
    padding = 1
  },
  sections = {
    lualine_a = {
      {"mode", upper = true, icon = ""}
    },
    lualine_b = {
      {"branch", icon = ""},
      {
        "diff",
        colored = true,
        symbols = {
          added = " ",
          modified = " ",
          removed = " "
        },
        color_added = "#88cf88",
        color_modified = "#a0bfdf",
        color_removed = "#ffa0a0"
      }
    },
    lualine_c = {{"filename", file_status = true, icon = "", shorten = true}},
    lualine_x = {{"encoding"}, {"filetype", colored = true}},
    lualine_y = {"progress"},
    lualine_z = {"location"}
  },
  inactive_sections = {
    lualine_a = {},
    lualine_b = {},
    lualine_c = {"filename"},
    lualine_x = {"location"},
    lualine_y = {},
    lualine_z = {}
  },
  extensions = {}
}
</details>

**Comment by ronniedroid** [comment]
Sorry, forgot to check closed issues

**Comment by ronniedroid** [comment]
Turned out the other person had closed the issue without a solution,  so I am reopening this one.

**Comment by shadmansaleh** [comment]
The options `shorten` and `full_path` were removed . The've been replaced by a single `path` option. The error was ment to let you know of the changes since you were using `shorten` . Like the message says see the help section or  [README](https://github.com/hoob3rt/lualine.nvim#component-specific-options)

**Comment by ronniedroid** [comment]
Though that is the `filename` component, not the `filetype` component. The error message needs correction.

**Comment by shadmansaleh** [comment]
You're right . I'll change that right away :)

**Comment by shadmansaleh** [comment]
@ronniedroid fixed in #237
