### ISSUE TITLE
Feat: remove option to configure through vimscript

### ISSUE THREAD

**Issue by hoob3rt** [hoob3rt/lualine.nvim#242]
I will remove the option to configure lualine through vimscript sooner or later (probably sooner).

Why? Vimscript sucks. My eyes hurt when looking at the `let g:lualine` syntax. Way easier and less error prone to just do
```
lua << EOF
...
EOF
```
The config parser process & loading will be also easier.
I'm also considering changing the config structure slightly
from 
```lua
require'lualine'.setup {
  options = {theme = 'gruvbox'},
  sections = {lualine_a = {'mode', 'g:coc_status'}},
  extensions = {'quickfix'}
}
```
to 
```lua
require'lualine'.setup {
  options = {theme = require 'lualine.themes.gruvbox'},
  sections = {lualine_a = {require 'lualine.components.mode', vim.g.coc_status}},
  extensions = {require 'lualine.extensions.quickfix'}
}
```
This is impossible to do in vimscript. I wanna do this because there is no need for us to do extensive config parsing when both of these configs are just as easy to implement. The second makes more sense, you are writing lua in lua, not lualine syntax in lua.

**Comment by shadmansaleh** [comment]
```
to

require'lualine'.setup {
  options = {theme = require 'lualine.themes.gruvbox'},
  sections = {lualine_a = {require 'lualine.components.mode', vim.g.coc_status}},
  extensions = {require 'lualine.extensions.quickfix'}
}
```

Is easy to configure no longer a goal ? 

> . I wanna do this because there is no need for us to do extensive config parsing when both of these configs are just as easy to implement

They are already implemented . Not like they need to be newly implemented.

> The second makes more sense, you are writing lua in lua, not lualine syntax in lua

lualine just requires you to type in names . Now with names you'll have to type in long require statements containing path .Weren't you talking about configuration bloat few days back ?

> vim.g.coc_status

This will not work . I'll let you figure out why ..

IMO This is a very bad idea.

**Comment by hoob3rt** [comment]
> IMO This is a very bad idea.

The idea might not be the best but we are moving away from vimscript anyway. My bad for not thinking #113 through

**Comment by shadmansaleh** [comment]
Ok I'm out . Bye

**Comment by hoob3rt** [comment]
> Ok I'm out . Bye

Rage quitting because I want to remove vimscript suport? Take care man and thank you for your contributions :)

**Comment by shadmansaleh** [comment]
> Rage quitting because I want to remove vimscript suport? 

Not really vimscript . I just don't like requires in configuration :(

**Comment by hoob3rt** [comment]
> > Rage quitting because I want to remove vimscript suport?
> 
> Not really vimscript . I really don't like requires in configuration :(

Then you rage quit because I was considering an idea.

**Comment by desprit** [comment]
> Then you rage quit because I was considering an idea.

I'm pretty sure that's not what's happened. #113 and #242 are quite contradictory. Saying you want to support configuring through vimscript and then saying you are moving lua-exclusive configs is not community-friendly. Especially with explanations like "Vimscript sucks. My eyes hurt.".

**Comment by hoob3rt** [comment]
@desprit 
* I know lua way better than vimscript ( if I had to degug an error in vimscript config then I couldn't do it with ease)
* i couldn't see a lot of lua plugins giving that option so I don't see a reason to break the norm
* wrapping code inside lua<<eof imo easier then fighting with vimscript indentation


> Saying you want to support configuring through vimscript and then saying you are moving towards lua-exclusive configs is not community-friendly.

Opinions change.
