### ISSUE TITLE
Feat: Custom extensions? 

### ISSUE THREAD

**Issue by HiPhish** [hoob3rt/lualine.nvim#246]
Lualine allows users to specify a different status line for certain file types, but it appears that the mechanism is limited to a set of included extensions. I would like to add my own extensions for certain file types like `help`, `man`, `info` or different REPL style buffers. Most of the information in a regular buffer status line is useless in those special buffers.

I can imagine something like this:

```lua
local man = require 'my_stuff.lualine.extensions.man'  -- My own custom extension
require 'lualine'.setup {
    extensions = {
        'nerdtree',
        man
    }
}
```

The module `my_stuff.lualine.extensions.man` would return a table which has the same format as the tables used for the included extensions as well. Being able to have a different status line for different file types is why I want to switch to Lualine in the first place.

**Comment by hoob3rt** [comment]
I missed that, good catch. I will implement it today :)

**Comment by hoob3rt** [comment]
Okay, that was really straightforward. https://github.com/hoob3rt/lualine.nvim/commit/9d9ee2d60ed22a603bd92afabd38e10eb15b413b

Custom extensions now can be loaded exatcly as you suggested here, if you create a nice extension then please submit a pr :)

**Comment by HiPhish** [comment]
Thank you.

> if you create a nice extension then please submit a pr :)

Sure, will do.
