### ISSUE TITLE
Bug: Filename path unnecessarily shortened

### ISSUE THREAD

**Issue by alexander-born** [hoob3rt/lualine.nvim#249]
### Self Checks
- [x] I'm using the latest lualine and neovim nightly.
- [x] I didn't find the issue in exsisting issues or prs.

### How to reproduce the problem
open file with relative filename > 40 characters

### Actual behaviour
filename is shortened

### Expected behaviour
filename is not shortened when enough space available

### Aditional information
see lualine.nvim/lua/lualine/components/filename.lua:56
```lua
  local estimated_space_available = 40
    if windwidth <= 84 or #data > estimated_space_available then
      data = shorten_path(data, path_separator)
    end
```

### Minimal config to reproduce the issue

<details>
<summary>Config</summary>

require'lualine'.setup {
  sections = {
    lualine_c = {{'filename', path = 1}},
  },
}
</details>

**Comment by hoob3rt** [comment]
> filename is not shortened when enough space available

This sounds easy enough, but it's not. To achieve the expected behavior I'd have to keep track of the lenght of all components(I think). I am planning on doing it somewhere down the line...

**Comment by alexander-born** [comment]
Would you be open to a PR where `estimated_space_available` is replaced by a option parameter `shorten_path_above_char_limit` with a default value of 40? Alternatively a flag to enable/disable the path shortening all together?

**Comment by hoob3rt** [comment]
> Would you be open to a PR where `estimated_space_available` is replaced by a option parameter `shorten_path_above_char_limit` with a default value of 40? 

This is not necessary imo, unnecessary complications to the config.

> Alternatively a flag to enable/disable the path shortening all together?

I don't think that's needed either. If you want just the filename with no shortening you can already achieve that by using `vim.fn.expand()` just like it's in lualine's codebase.

Closing this as it's a subissue of #225

**Comment by alexander-born** [comment]
Thanks for the hint, using `vim.fn.expand()` directly now and does exactly what I want.
