### ISSUE TITLE
Change theme structure

### ISSUE THREAD

**Issue by hoob3rt** [hoob3rt/lualine.nvim#25]
> I think mirroring theme on left(A,B,C) and right(X,Y,Z) is limiting.
> I kind of like the left and right structure in lightline.
> can we have something like that in lualine ?

I personally can't see how lualine's theme structure is limiting compared to `lightline`. Could you elaborate on what exactly are you missing?

_Originally posted by @shadmansaleh in https://github.com/hoob3rt/lualine.nvim/pull/23#issue-548058407_

**Comment by samirettali** [comment]
I think he is referring to the fact that he can't change, for example, the background color of block `a` to be red and of block `z` to be green, they must be either both red or both green.

I modified my local configuration to be able to set individual block colors and not in a mirrored way, I'd be happy to open a PR if needed.

**Comment by shadmansaleh** [comment]
I'm voting to close this issue . Since it was started on my comment . I donn't thunk it's nessary any more.
