### ISSUE TITLE
Displaying tabs indices

### ISSUE THREAD

**Issue by davideliseo** [hoob3rt/lualine.nvim#254]
Hi, I hope you all are doing great. 

Is there any way lualine can show the number/index of a tab up in the tabline? I searched the docs, but I couldn't find anything helpful. 

I'm currently using the default configuration (or at least the one posted in the README), and tabs only display the name of the file. 

Thanks for this amazing plugin, by the way!

**Comment by hoob3rt** [comment]
if you want an indicator of the current tab then you can do
```lua
local function num() return vim.fn.tabpagenr() end
require'lualine'.setup {sections = {lualine_a = {num}}}
```
If you want a full fledged tabline then I suggest using something like [this](https://github.com/akinsho/nvim-bufferline.lua)

**Comment by David-Kunz** [comment]
Note: It only works if you actually return a string, i.e.
```lua
local function num() return tostring(vim.fn.tabpagenr()) end
```

**Comment by shadmansaleh** [comment]
Not necessarily not it gets converted to string if a string isn't returned 

https://github.com/shadmansaleh/lualine.nvim/blob/260133ce631da2047a00b55f25ffc553c2ab4318/lua/lualine/components/special/function_component.lua#L10-L15

**Comment by David-Kunz** [comment]
Interesting... But if I leave `tostring` out, the function doesn't display anything.

**Comment by shadmansaleh** [comment]
It works for me . To clarify you're on my fork right ?

**Comment by David-Kunz** [comment]
Hi @shadmansaleh , I didn't see that the url you've shown was in your fork. I'm using `hoob3rt/lualine.nvim`.

**Comment by shadmansaleh** [comment]
You probably should switch to that fork . See #311 to see whats changed. Until hoob3rt comes back I don't think there's any point of using this instead of the fork.

**Comment by David-Kunz** [comment]
Hi @shadmansaleh ,

Thank you for this information, I wasn't aware of this.

Best regards,
David
