### ISSUE TITLE
Tab info centered on top of the window?

### ISSUE THREAD

**Issue by rickalex21** [hoob3rt/lualine.nvim#261]
Hello, thanks for this great plugin. Is it possible to have the tab info centered on top of the window instead
of aligned to the left? On the status line, it's fine. Every file I go to I can see the info
on the bottom but on the tab info everything is on the left aligned.

![](https://i.imgur.com/pDUGIQ1.png)

Another thing is when I try to pass a table to section I get an error. Instead I just duplicate the
code into ```section``` and ```tabline```. 

```lua
	local tline = {
		lualine_a = {'mode'},
		lualine_b = { 'branch',
			{
			  'diff',
			  color_added = "#91B362",
			  color_modified = "#6994BF",
			  color_removed = "#D96C75"
			},
		  },
		lualine_c = {file,path,file },
		lualine_x = {'encoding', 'fileformat', 'filetype'},
		lualine_y = {'progress'},
		lualine_z = {'location'}
		}
-- More code here
	  tabline = { tline },
```

```vim
Error executing vim.schedule lua callback: .../plugged/vim-plug/lualine.nvim/lua/lualine/component.lua:29: attempt to compare number with string
````

Here is my configuration:

```lua
	local function path()
	return vim.fn.expand('%:p')
	end

	local purple =  "#B685B6"
	local file = { 'filename', color = {fg = purple}, file_status = true, icon ='📝'}

	require'lualine'.setup {

	  options = {
		icons_enabled = true,
		theme = 'onedark',
		component_separators = {'', ''},
		section_separators = {'', ''},
		disabled_filetypes = {}
	  },
	  sections = {

		lualine_a = {'mode'},
		lualine_b = { 'branch',
			{
			  'diff',
			  color_added = "#91B362",
			  color_modified = "#6994BF",
			  color_removed = "#D96C75"
			},
		  },
		lualine_c = {file,path,file },
		lualine_x = {'encoding', 'fileformat', 'filetype'},
		lualine_y = {'progress'},
		lualine_z = {'location'}
	

		  },
	  inactive_sections = {
		lualine_a = {'filename'},
		lualine_b = {path},
		lualine_c = {'filename'},
		lualine_x = {'location'},
		lualine_y = {},
		lualine_z = {}
	  },
	  tabline = {

		lualine_a = {'mode'},
		lualine_b = { 'branch',
			{
			  'diff',
			  color_added = "#91B362",
			  color_modified = "#6994BF",
			  color_removed = "#D96C75"
			},
		  },
		lualine_c = {file,path,file },
		lualine_x = {'encoding', 'fileformat', 'filetype'},
		lualine_y = {'progress'},
		lualine_z = {'location'}
	

	  },
		extensions = { 'fugitive', 'nvim-tree' }
	}
end


```

**Comment by shadmansaleh** [comment]
> Hello, thanks for this great plugin. Is it possible to have the tab info centered on top of the window instead
of aligned to the left?

 I'm not entirly sure what you mean here .I'm assuming Yiy want to see  file, path in the middle . You can try something like

```lua
lualine_c = {"'%='", file,path,file }
```

>Another thing is when I try to pass a table to section I get an error. Instead I just duplicate the
code into section and tabline.

Run it through `vim.deepcopy()`. Tables are copy by refference in lua.
```lua
locak config = {
lualine_a = {...},
lualine_b = {...},
...
}
require'lualine'.setup {
section = vim.deepcopy(config),
tabline = vim.deepcopy(config)
}
```

**Comment by rickalex21** [comment]
>I'm not entirly sure what you mean here . ```lualine_c = {"'%='", file,path,file }```

That is better than having it in the far left but what I meant is putting that information above the
window split. Look at the two circles that I made in the picture. The same information on the bottom
right I would like it to show on the top right. Which would make it show above the window split.

This is what I mean, each window split has the info on top like the status line.

![](https://i.imgur.com/nk35uCZ.png)

>vim.deepcopy()

Thanks that works I did not now I had to call a vim command to make that happen. I'm fairly
new to lua.

**Comment by shadmansaleh** [comment]
>That is better than having it in the far left but what I meant is putting that information above the
window split. Look at the two circles that I made in the picture.

This is not directly supported by (neo)vim . As tablines aren't window specific . Some tabline plugin might try to implement it by mesuring window width and applying proper spacing . But it's out of scope of lualine as it's a statusline plugin

**Comment by rickalex21** [comment]
>by mesuring window width and applying proper spacing 

Gotcha, thanks. I'm going to have to figure out a vim hack for this or be happy with the
info showing in the middle of the terminal.

**Comment by rickalex21** [comment]
@shadmansaleh Your suggestion lags on start up, do you know why? It takes a while for me to use my
keyboard when it starts up. After maybe 3 seconds or so I can move.

>lualine_c = {"'%='", file,path,file }

Once I remove the ```"'%='"``` it works fine I can instantly move once I see the buffer.

**Comment by shadmansaleh** [comment]
> Your suggestion lags on start up, do you know why? It takes a while for me to use my
keyboard when it starts up. After maybe 3 seconds or so I can move.

There might be a bug in that component . I had that happen to me once but later couldn't reproduce it. Re-lace it with

```lua
function() return '%=' end
```

**Comment by rickalex21** [comment]
Thanks, that took care of the problem. 👍
