### ISSUE TITLE
Bug: E5108: Error executing lua [string ":lua"]:1: E539: Illegal character <U>

### ISSUE THREAD

**Issue by rickalex21** [hoob3rt/lualine.nvim#267]
### Update

I solved the problem by renaming my backup files and changing the way backup files are saved but this
is still a problem in lualine. This does break one of my personal plugins that I will have to fix.

**solution**
Change all the '%' into '-' for backup files.

```vim
autocmd settings BufWritePre * let &bex =  '@' . strftime("%H:%M:%S-%F").'-'.substitute(fnamemodify(expand('%'),":p:h"),'\v.(.*$)','\=tr(submatch(1),"/","-")','g')

set backup
execute "set backupdir=".$vim."/.data/backup/"
```
### Self Checks

- [X] I'm using the latest lualine and neovim nightly.
- [X] I didn't find the issue in exsisting issues or prs.

### How to reproduce the problem

Create a file named like this.

```text
touch %Users%user%somefile.vim@09:42:34-2021-05-30
```
Open the file: 

```vim
vs \%Users\%user\%somefile.vim@09:42:34-2021-05-30
```

Exit the file with ```:bd```. You will get the following error:

```vim
Error detected while processing BufLeave Autocommands for "*":
E5108: Error executing lua [string ":lua"]:1: E539: Illegal character <U>
Error detected while processing WinLeave Autocommands for "*":
E5108: Error executing lua [string ":lua"]:1: E539: Illegal character <U>
Press ENTER or type command to continue
```

### Actual behaviour

It doesn't do well with long file names or weird long backup file names like those produced by nvim.

### Expected behaviour

Should be able to handle file names like that. It looks like the problem might be in the Autocmds
when leaving the file.

### Additional information

I use these backup files, since I don't commit often I go back to these files to diff against if there
is a problem. This was the old way that I named files, see the update above.

```vim
autocmd settings BufWritePre * let &bex = '@' . strftime("%H:%M:%S-%F")
set backup
execute "set backupdir=".$vim."/.data/backup//"
execute "set directory=".$vim."/.data/swap//"
set writebackup
set backupcopy=yes
```

### Minimal config to reproduce the issue

<details>
<summary>Config</summary>

```vim
call plug#begin('~/.config/nvim/plugged')
	Plug 'hoob3rt/lualine.nvim'
call plug#end()
lua<<EOF
	require'lualine'.setup {}
EOF
finish
```

</details>

**Comment by shadmansaleh** [comment]
I can't reproduce it . What os are you using ?

**Comment by rickalex21** [comment]
@shadmansaleh Mac OS 11.5 . I did solved the problem by renaming files without the '%' in them.

**Comment by shadmansaleh** [comment]
I tried on linux no error happened . I think this might be a neovim bug

**Comment by rickalex21** [comment]
@shadmansaleh Could be and if it is who knows how long that will take to fix, they have a lot of work. I've been waiting on one of their bug fixes for a while now.

**Comment by shadmansaleh** [comment]
> I've been waiting on one of their bug fixes for a while now

Well they are just volunteers. If it's bugging you you could try to fix it . there's instruction on porting vimpach [here](https://github.com/neovim/neovim/wiki/Merging-patches-from-upstream-Vim)

If you're talking about `getreginfo` issue . It's probably new vim function that hasn't been ported to neovim yet . The docs on `map-leader` was probably ported in a different patch and no one noticed getreginfo isn't there yet .

**Comment by rickalex21** [comment]
@shadmansaleh It does not bother me, I haven't been in the vim world in a while. I've been busy with
other things. I understand that they are volunteers and have other priorities. 
Thanks
