### ISSUE TITLE
Bug: lualine goes blank after calling NvimTreeToggle

### ISSUE THREAD

**Issue by dragondove** [hoob3rt/lualine.nvim#268]
### Self Checks

- [X] I'm using the latest lualine and neovim nightly.
- [X] I didn't find the issue in exsisting issues or prs.

### How to reproduce the problem
1. install both nvim-tree and lualine plugins.
2. open a file in nvim.
3. call :NvimTreeToggle.
4. lualine gets into the tree buffer.
5. call :NvimTreeToggle again.
6. lualine shows blank in current buffer.
### Actual behaviour
lualine goes blank.
### Expected behaviour
lualine should appears again after toggle nvimtree.
### Minimal config to reproduce the issue

<details>
<summary>Config</summary>

</details>

**Comment by oblitum** [comment]
This happens if any buffer where lualine is deactivated is focused and gets closed while focused.

**Comment by ful1e5** [comment]
@dragondove Which colorscheme are you using?

**Comment by dragondove** [comment]
> 
> 
> @dragondove Which colorscheme are you using?

I'm using [zephyr](https://github.com/glepnir/zephyr-nvim) . Does it relate to this issue? The config of lualine I used is from evil_lualine.

**Comment by shadmansaleh** [comment]
what's most likely happening is the active status isn't being enabled due to none of the event we look for being triggured

We probably need aditional event to catch this case here:

https://github.com/hoob3rt/lualine.nvim/blob/9726824f1dcc8907632bc7c32f9882f26340f815/lua/lualine/init.lua#L173

@dragondove evil_lualine doesn't configure inactive_status that's why you're probably seeing lualine disapear . Does leaving the window and entering it again bring back lualine ?

**Comment by dragondove** [comment]
> 
> 
> what's most likely happening is the active status isn't being enabled due to none of the event we look for being triggured
> 
> We probably need aditional event to catch this case here:
> 
> https://github.com/hoob3rt/lualine.nvim/blob/9726824f1dcc8907632bc7c32f9882f26340f815/lua/lualine/init.lua#L173
> 
> @dragondove evil_lualine doesn't configure inactive_status that's why you're probably seeing lualine disapear . Does leaving the window and entering it again bring back lualine ?

yes, If I firstly switch to the editing buffer(By C-w w), lualine will be there.

**Comment by dragondove** [comment]
It seems this bug disapears, but I don't know why, maybe it is caused by a specific version of neovim. Anyway, it works fine now.
