### ISSUE TITLE
Specifying just the symbol for `filetype` component?

### ISSUE THREAD

**Issue by macintacos** [hoob3rt/lualine.nvim#270]
### Requested feature

I basically want to just be able to show an icon for the filetype plus the file name, but it doesn't seem like I'm able to do that out of the box. I'm not that great at hacking Lua so I'm not sure how to get it done myself, but if I find a workaround I'll post it here in the meantime.

**Comment by shadmansaleh** [comment]
I think it's a duplicate of #233 which should be resolved by #256

**Comment by macintacos** [comment]
Oh yeah that looks exactly like what I need, thanks @shadmansaleh! I'll close this out in that case.
