### ISSUE TITLE
Question: How to set absolute path.

### ISSUE THREAD

**Issue by g96k** [hoob3rt/lualine.nvim#271]
Im new to lua i tried playing around with the setup function but i wasnt able to make it display the absolute path of a file. Can you give me an example one liner please.

**Comment by xiyaowong** [comment]
```lua
{
      'filename',
      path = 2 -- 0 = just filename, 1 = relative path, 2 = absolute path
    }
```

**Comment by shadmansaleh** [comment]
From README
```lua
sections = {
  lualine_a = {
    {
      'filename',
      file_status = true, -- displays file status (readonly status, modified status)
      path = 2 -- 0 = just filename, 1 = relative path, 2 = absolute path
    }
  }
}
```

**Comment by g96k** [comment]
last time it copied it it didnt work. 

however now except the absolute path i have it one more time

![image](https://user-images.githubusercontent.com/69681813/122052121-041f4200-cdee-11eb-8047-b463e3857848.png)

**Comment by g96k** [comment]
Im sorry it didnt work when i tried to copy paste it the first time. 
Thank you

**Comment by diegoulloao** [comment]
Not working for me...

**Comment by DedaDev** [comment]
Keep in mind its double nested curly so 
`lualine_c = { { 'filename'... } }`

**Comment by picrots** [comment]
The entire `sections` option doesn't work for me.
I can change other options but whatever I set inside `sections` won't get reflected in the result.
