### ISSUE TITLE
Question: How to change section separator

### ISSUE THREAD

**Issue by nathom** [hoob3rt/lualine.nvim#272]
This is how it is now:

<img width="561" alt="image" src="https://user-images.githubusercontent.com/74019033/121618502-b8e6e700-ca1b-11eb-8d65-4f60d6abcf78.png">

I'd like the triangular section separators to be vertical lines instead.

**Comment by shadmansaleh** [comment]
https://github.com/hoob3rt/lualine.nvim#separators
