### ISSUE TITLE
Lualine Integration with 'akinsho / nvim-bufferline.lua'

### ISSUE THREAD

**Issue by Trid-collab** [hoob3rt/lualine.nvim#273]
I have started using 'akinsho / nvim-bufferline.lua'. Is it possible to integrate the Lualine features with those of 'bufferline' . Basically I was wanting color highlighting I am getting in statusline in the tabline along with the benefits of the "akinsho / nvim-bufferline.lua" plugin. 

I like how earlier airline enabled the highlighting of bufferline

**Comment by shadmansaleh** [comment]
Most recent colorschems have support for both of these plugins . If you're using one of those they should look similar . If your colorscheme doesn't have support for these plugins then you could try adding support to the colorcheme or configure them to look similar . I don't think there's any reason lualine or nvim-bufferline would make each other look similar. After all they are separate plugins .

**Comment by hoob3rt** [comment]
Spot on, I don't have any plans to work with nvim-bufferline as of right now. The colorschemes are the same so I don't see an issue here.
