### ISSUE TITLE
`VertSplit` & `StatusLine` crossover

### ISSUE THREAD

**Issue by ful1e5** [hoob3rt/lualine.nvim#274]
### Self Checks

- [x] I'm using the latest lualine and neovim nightly.
- [x] I didn't find the issue in exsisting issues or prs.

### Problem Description
Currently, I am developing [onedark](https://github.com/ful1e5/onedark.nvim) colorscheme for nvim. After setting lualine colors to dark seems like it's one pixel off on the right side. It's only happening on `Statusbar` and `VertSplit` crossover. 

It's lualine problem or I am doing something stupid with colorscheme.

https://user-images.githubusercontent.com/24286590/122219430-0c01e380-cecd-11eb-9544-91c15cd27b36.mp4

#### upper `hsplit` **[working]**
![upper-split](https://user-images.githubusercontent.com/24286590/122219852-774bb580-cecd-11eb-87b4-51f43f2a44c4.png)

#### Nvimtree crossover
![nvimtree](https://user-images.githubusercontent.com/24286590/122219880-7dda2d00-cecd-11eb-86f8-9eefd1dc061a.png)

#### lower `hsplit`
![lower-split](https://user-images.githubusercontent.com/24286590/122219894-80d51d80-cecd-11eb-9899-4669e09cd02f.png)

**Comment by hoob3rt** [comment]
This gap you are seeing is colored according to `StatusLine` color group. I don't getting rid entirely is possible and last time I checked all statusline plugins behave that way. neoviim (and vim) doesn't split the bottom-most statusline and that's why you are seeing this block.

**Comment by ful1e5** [comment]
@hoob3rt How I check lualine is active or not inside Lua?

**Comment by shadmansaleh** [comment]
@ful1e5 check value of statusline option.

Here's the part that sets statusline option
https://github.com/hoob3rt/lualine.nvim/blob/9726824f1dcc8907632bc7c32f9882f26340f815/lua/lualine/init.lua#L166-L178

**Comment by ful1e5** [comment]
Gotcha :+1: 
```lua
if string.find(vim.o.statusline, "lualine") then
  print("Lualine is active")
else
  print("Lualine is inactive")
end
```
