### ISSUE TITLE
Feat: Change bar background independent of section C

### ISSUE THREAD

**Issue by lokesh-krishna** [hoob3rt/lualine.nvim#282]
### Requested feature
Could you please consider making it possible to change the bar background color without deriving it from the section C background color?

### Motivation
Use a different color for section C instead of having to use it to set the background color.

**Comment by shadmansaleh** [comment]
Not sure what you're asking for . Can you elaborate ?

Where will the background color be ?

**Comment by lokesh-krishna** [comment]
I was hoping we could get a new option that specifically set the background color. Right now, the background color, to the best of my understanding, is the color that you set for section C. I would like to be able to use a separate color for section C and background. 

Attaching a screenshot to help elucidate what I'm trying to say:
![swappy-20210727_132135](https://user-images.githubusercontent.com/20235646/127117841-00d63c9c-8b9e-4ad4-af17-9863255b314a.png)

I would like to use two distinct colors for the areas within the two boxes instead of both using the color set for section C.

**Comment by shadmansaleh** [comment]
You could use `color` option in component to achive that .

The thing is there's no such thing as background in terms of lualine . unlike lightline/galaxyline/airline lualine isn't separated in left/right section . That's why I don't think background makes much sense in these terms.

**Comment by lokesh-krishna** [comment]
Thanks a lot for explaining :)
