### ISSUE TITLE
Bug: LuaLine colors mess up when I open a file with syntax on

### ISSUE THREAD

**Issue by surmish** [hoob3rt/lualine.nvim#285]
latest for both (have seen this issue even in bufferline)

### Self Checks

- [x ] I'm using the latest lualine and neovim nightly.
- [x ] I didn't find the issue in exsisting issues or prs.

### How to reproduce the problem (See EASIER_STEPS for easier steps)

- Keep colorscheme desert (at least one colorscheme must be set) in your init.lua file 
- Start neovim by opening empty file. You should see this (lualine with correct colors)
![image](https://user-images.githubusercontent.com/33273194/125128968-9fd16480-e0b3-11eb-89b6-8479dde617b9.png)
- open a file with vim syntax support (e.g. a .cpp file)
- make sure treesitter or any other plugin affecting highlighting is disabled.

 ### EASIER_STEPS

The whole bug can be narrowed down by doing this, on the vim commandline source any colorscheme:

```
:source /u/urmish/usr/local/share/nvim/runtime/colors/desert.vim
```
then lualine/bufferline colors mess up.

But after this, if I run
```
colorscheme desert
```
Lualine colors are restored.

### Actual behaviour
![image](https://user-images.githubusercontent.com/33273194/125129034-b972ac00-e0b3-11eb-811d-9e6cbc003450.png)

### Expected behaviour
![image](https://user-images.githubusercontent.com/33273194/125128871-7e707880-e0b3-11eb-98a0-bd5e05b0eda6.png)

### Additional information
After some basic profiling I noticed this, when I open/create a program file nvim loads the colorscheme (desert.vim) like so

```
I] ➜ g ^SCRIPT e_cpp.log
SCRIPT  /usr/local/share/nvim/runtime/syntax/synload.vim
SCRIPT  /usr/local/share/nvim/runtime/syntax/syncolor.vim
SCRIPT  /usr/local/share/nvim/runtime/colors/desert.vim
SCRIPT  /usr/local/share/nvim/runtime/ftplugin/cpp.vim
SCRIPT  /usr/local/share/nvim/runtime/ftplugin/c.vim
SCRIPT  /usr/local/share/nvim/runtime/indent/cpp.vim
SCRIPT  /u/urmish/.vim/plugged/vim-clang-format/autoload/clang_format.vim
```
 
But if colorscheme is not set (in init.lua or vimrc or init.vim), then it isn't loaded at runtime (there is no default.vim colorscheme). 
```
[I] ➜ g ^SCRIPT e_cpp_2.log
SCRIPT  /usr/local/share/nvim/runtime/syntax/synload.vim
SCRIPT  /usr/local/share/nvim/runtime/syntax/syncolor.vim
SCRIPT  /usr/local/share/nvim/runtime/ftplugin/cpp.vim
SCRIPT  /usr/local/share/nvim/runtime/ftplugin/c.vim
SCRIPT  /usr/local/share/nvim/runtime/indent/cpp.vim
SCRIPT  /u/urmish/.vim/plugged/vim-clang-format/autoload/clang_format.vim
```
In this case the lualine colors are as expected
![image](https://user-images.githubusercontent.com/33273194/125130426-cf816c00-e0b5-11eb-9ceb-9929a6a1dddc.png)

### Minimal config to reproduce the issue
```lua
require('packer').startup(function()
  use { 'hoob3rt/lualine.nvim', requires = {'kyazdani42/nvim-web-devicons', opt = true} }
end)
require('lualine').setup{}
```

What does `colorscheme <colorscheme>` command do extra in neovim/vim than simply  `source<colorscheme>.vim`?

**Comment by shadmansaleh** [comment]
> What does colorscheme <colorscheme> command do extra in neovim/vim than simply source<colorscheme>.vim?

`:corscheme` trigures `ColorScheme` event . lualine restores it's colors on that event.

Usually colorschemes start with `:hi clear` that clears all current highlight groups includeing the ones lualine create . If you run `hi clear` or by sourceing a file there's no way for lualine to know it has happened.

So what you're describing here is expected behavior not a bug . Solution would not to source colorscheme instead use `:colorscheme` command.

**Comment by surmish** [comment]
I am not sourcing the script. The `colorscheme` command is doing the right thing yes, but whenever a file is opened the `source <colorscheme.vim>` command is ran without my control over it. I tried this on multiple OSes (centos(konsole) and ubuntu (kitty and gnome)). I tried this with/without tmux, but see the same behavior everywhere. I want to say this isn't limited to lualine. I have seen the same behavior with bufferline and airline. So a better place to ask would be neovim (I don't see the same thing in vim of course. It's a rather blatant change). @shadmansaleh Do you see the same behavior? I also tried a minimal nvim config (with no plugins except lualine and no extra installed colorschemes)

**Comment by shadmansaleh** [comment]
> Do you see the same behavior? 

No
> but whenever a file is opened the source <colorscheme.vim> command is ran without my control over it. I tried this on multiple OSes (centos(konsole) and ubuntu (kitty and gnome))

this is not neovim's behavior . There must be something that in your config that is causing it.

> So a better place to ask would be neovim

This is not regular behavior from neovim . I'm not sure if opening a issue for debugging your config will be a good idea . You can make a post in [neovim discource](https://neovim.discourse.group) that's more or less support forum .

**Comment by shadmansaleh** [comment]
delete [this](https://github.com/surmish/dotfiles/blob/4c5e7f0847e9f2393d1fe27f90d3227404ae3fe6/init.lua#L370) line . Unlike vim syntax is on by default in neovim.

**Comment by surmish** [comment]
That worked. I thought I tried a minimal config and saw the issue but apparently not. Will close this for now. Thanks.
