### ISSUE TITLE
Bug: diagnostic info from nvim_lsp not showing

### ISSUE THREAD

**Issue by benfrain** [hoob3rt/lualine.nvim#292]
### Self Checks

- [X ] I'm using the latest lualine and neovim nightly.
- [X ] I didn't find the issue in existing issues or prs.

### How to reproduce the problem
Open a file where LSP info should display.

### Actual behaviour
I get the error `no sources for diagnostics configured`.

### Expected behaviour
nvim_lsp diagnostic info showing in Lualine

### Additional information
compe is using `nvim_lsp` with no issues in the same config. That is working correctly with this:

```
require "compe".setup {
  documentation = true,
  source = {
    path = true,
    nvim_lsp = true
  }
}


```

### Minimal config to reproduce the issue

<details>
<summary>Config</summary>

```
require "lualine".setup {
  options = {
    icons_enabled = true,
    theme = "everforest",
    component_separators = {"", ""},
    section_separators = {"", ""},
    disabled_filetypes = {}
  },
  sections = {
    lualine_a = {"mode", "paste"},
    lualine_b = {"branch", "diff"},
    lualine_c = { "diagnostics", source = "nvim_lsp" },
    lualine_x = {"filetype"},
    lualine_y = {"progress"},
    lualine_z = {"location"}
  },
  inactive_sections = {
    lualine_a = {},
    lualine_b = {},
    lualine_c = {"filename"},
    lualine_x = {"location"},
    lualine_y = {},
    lualine_z = {}
  },
  tabline = {},
  extensions = {}
}
```

</details>

**Comment by shadmansaleh** [comment]
Did you see my [reply](https://github.com/hoob3rt/lualine.nvim/issues/291#issuecomment-879034974) ?

**Comment by benfrain** [comment]
@shadmansaleh I did see that. I have tried all these variations but still get the same error:

```
lualine_c = { "diagnostics", sources = "nvim_lsp"},
lualine_c = { "diagnostics", sources = nvim_lsp},
lualine_c = { "diagnostics", source = "nvim_lsp"},
lualine_c = { "diagnostics", source = nvim_lsp},
```

**Comment by shadmansaleh** [comment]
Correct one is 

```lua
lualine_c = { "diagnostics", sources = {"nvim_lsp"}},
```

**Comment by benfrain** [comment]
Hi, ha :) , tried that one now but same issue. I still get the `no sources for diagnostics configured` message and nothing displaying.

Just to test my assumptions, if I have nvim_lsp providing the auto complete for nvim-compe successfully (which I do), I'm thinking this should be working with that config?

**Comment by shadmansaleh** [comment]
Very strange .
```lua
     {'diagnostics',  sources={'nvim_lsp'}},
```
This is copy pasted from my config . I'm using nvim_lsp with compe & lualine too it's working fine me 😅

**Comment by benfrain** [comment]
@shadmansaleh any chance you could share your init.lua in a gist or similar? Be keen to see if there’s something else I’ve not got set correctly

**Comment by shadmansaleh** [comment]
Sorry my dot files are private ;)

**Comment by JSchrtke** [comment]
Same issue here, this is the entire config I tried for lualine.
```lua
" ### Configure lualine.nvim ###
require("lualine").setup{
    options = {
        theme = 'auto',
        component_separators = {'', ''},
        section_separators = {'', ''},
    },
    sections = {
        lualine_a = {'mode'},
        lualine_b = {'filename'},
        lualine_c = {'branch'},
        lualine_d = {'diagnostics',  sources={'nvim_lsp'}},
        lualine_x = {'encoding', 'fileformat', 'filetype'},
        lualine_y = {'progress'},
        lualine_z = {'location'}
    },
}
```

**Comment by benfrain** [comment]
Thanks @tonymugen seems to have done the job for me too. For future travelers, here is my amended sections, section:

```
  sections = {
    lualine_a = {"mode", "paste"},
    lualine_b = {"branch", "diff"},
    lualine_c = {
      {"filename", file_status = true, full_path = true},
      {
        {"diagnostics", sources = "nvim_lsp"}
      }
    },
    lualine_x = {"filetype"},
    lualine_y = {
      {
        "progress"
      }
    },
    lualine_z = {
      {
        "location",
        icon = ""
      }
    }
  },

```

**Comment by JSchrtke** [comment]
@benfrain does that actually show any diagnostics for you though? I tried the exact thing you posted, and while it doesn't error out, It just displays nothing where I would expect diagnostics.

**Comment by benfrain** [comment]
@JSchrtke seems to be:

<img width="494" alt="image" src="https://user-images.githubusercontent.com/1318466/126232648-656280d5-dca3-45dd-bbf4-cb0612f2aedf.png">

**Comment by JSchrtke** [comment]
I should go to sleep, I think we're talking about different things.

![126232648-656280d5-dca3-45dd-bbf4-cb0612f2aedf](https://user-images.githubusercontent.com/31078741/126237087-ca866b14-9f61-4f79-86a3-a078b31b0c2d.png)

Where are the diagnostics? What am I missing here :thinking:

**Comment by benfrain** [comment]
> I should go to sleep, I think we're talking about different things.
> 
> ![126232648-656280d5-dca3-45dd-bbf4-cb0612f2aedf](https://user-images.githubusercontent.com/31078741/126237087-ca866b14-9f61-4f79-86a3-a078b31b0c2d.png)
> 
> Where are the diagnostics? What am I missing here 🤔

No! I need more coffee. LMAO! You’re absolutely correct!

**Comment by shadmansaleh** [comment]
@tonymugen I should have noticed that issue on your configs . But totally missed that :P. Also the [README](https://github.com/hoob3rt/lualine.nvim#diagnostics-component-options) and vim docs definately show the correct way .

> I think wrapping things in ever more curly braces and having that work is a bit strange, I still think there just is something fundamentally wrong here

Ok `lualine_c` is list of components . Now when you need to configure a specific component you need to configure a component then you need to pass multiple values togather with the component that's why a table is needed hance extra braces . If you've a better idea do suggest :)

Also if diagnostics aren't apearing can you check what's the output of
```vim
:lua print(vim.inspect(require'lualine.components.diagnostics.'.get_diagnostics{'nvim_lsp'}))
```

Also the output of
```vim
:lua print(vim.lsp.diagnostic.get_count(0, 'Error'))
:lua print(vim.lsp.diagnostic.get_count(0, 'Warning'))
:lua print(vim.lsp.diagnostic.get_count(0, 'Information'))
:lua print(vim.lsp.diagnostic.get_count(0, 'Hint'))
```
To see if nvim_lsp is returning diagnostics.

**Comment by shadmansaleh** [comment]
Ok I can at least see a config issue with
https://github.com/hoob3rt/lualine.nvim/issues/292#issuecomment-882068345

> lualine_d = {'diagnostics',  sources={'nvim_lsp'}}

There's no such thing as lualine_d . Only a,b,c,x,y,z .

**Comment by tonymugen** [comment]
> @tonymugen I should have noticed that issue on your configs . But totally missed that :P. Also the [README](https://github.com/hoob3rt/lualine.nvim#diagnostics-component-options) and vim docs definately show the correct way .

Yep exactly. When messing around with it myself, I deleted the extra braces and that's when things stopped working, so that's how I found out. I am only superficially familiar with lua, I assume the extra braces are to pass a table rather than each component separately to a function.

**Comment by benfrain** [comment]
> ```viml
> lua print(vim.inspect(require'lualine.components.diagnostics'.get_diagnostics{'nvim_lsp'}))
> ```

I get:

```
{ {                                                                                                                                         
    error = 7,                                                                                                                              
    hint = 1,                                                                                                                               
    info = 0,                                                                                                                               
    warn = 0                                                                                                                                
  } } 
```

Then for each of the others I get:

7
1
0
0

So seems like info is there, just not displaying??

**Comment by JSchrtke** [comment]
@shadmansaleh 
> Ok lualine_c is list of components . Now when you need to configure a specific component you need to configure a component then you need to pass multiple values togather with the component that's why a table is needed hance extra braces . If you've a better idea do suggest :)

Alright, makes sense. Tbh, I'm not that familiar with lua, it seems to use curly braces for many things, it just seemed a bit weird to me at first glance.

> Ok I can at least see another config issue with
> #292 (comment)
>
>> lualine_d = {'diagnostics', sources={'nvim_lsp'}}
>
> There's no such thing as lualine_d . Only a,b,c,x,y,z .

Well, clearly I didn't read the docs properly. My bad

**Comment by shadmansaleh** [comment]
> Alright, makes sense. Tbh, I'm not that familiar with lua, it seems to use curly braces for many things, it just seemed a bit weird to me at first glance.

In lua only available compound data structure is dictionaries . They are defined with curly bases . Hance you see them everywhere .


@benfrain if you're still using https://github.com/hoob3rt/lualine.nvim/issues/292#issuecomment-882860826 . It still has config issue . This time you have one extra amd one missing pair of {} :P 

Try:
```lua
require'lualine'.setup{
  sections = {
    lualine_a = {"mode", "paste"},
    lualine_b = {"branch", "diff"},
    lualine_c = {
      {"filename", file_status = true, full_path = true},
      -- See the difference here
      {"diagnostics", sources = {"nvim_lsp"}}
    },
    lualine_x = {"filetype"},
    lualine_y = {
      {
        "progress"
      }
    },
    lualine_z = {
      {
        "location",
        icon = ""
      }
    }
  }
}
```

**Comment by benfrain** [comment]
<img width="569" alt="image" src="https://user-images.githubusercontent.com/1318466/126809878-0e492104-cdd0-4840-a6ca-1115d163516a.png">
Thanks @shadmansaleh working great with that!
