### ISSUE TITLE
Feat: option to configure fileformat icons

### ISSUE THREAD

**Issue by AckslD** [hoob3rt/lualine.nvim#294]
### Requested feature
The option so chose fileformat icons in a similar way to diagnostics.

### Motivation
Configurability

**Comment by shadmansaleh** [comment]
[filefornat](https://github.com/hoob3rt/lualine.nvim/blob/master/lua/lualine/components/fileformat.lua) is a really simple component . It can easily be replicated in your config if you want to change icons . Adding more options to something this simple feels unnessary to me :)

**Comment by AckslD** [comment]
Fair enough :)
