### ISSUE TITLE
Does lualine follow lush.nvim

### ISSUE THREAD

**Issue by ashincoder** [hoob3rt/lualine.nvim#296]
Hello,

There are many options in lush.nvim to display statusline colors. Does lualine follow lush.nvim color specs ?

**Comment by shadmansaleh** [comment]
No . lualine themes are different https://github.com/hoob3rt/lualine.nvim/blob/master/CONTRIBUTING.md#adding-a-theme

**Comment by ashincoder** [comment]
Thanks
