### ISSUE TITLE
Bug: components in tabline don't refresh as often as statusline

### ISSUE THREAD

**Issue by mystilleef** [hoob3rt/lualine.nvim#298]
### Self Checks

- [X ] I'm using the latest lualine and neovim nightly.
- [ X] I didn't find the issue in existing issues or prs.

### How to reproduce the problem

My tabline closely mirrors my statusline. Unfortunately, I notice components in the tabline, like the location one, don't refresh on events. I've attached a video showing the issue. 

https://user-images.githubusercontent.com/273399/125941429-40688f32-da03-4221-9dc7-e16572013976.mp4

**Comment by shadmansaleh** [comment]
nvim decided when it'll refresh tabline . There's atleast `:redrawstatus` that imediatly refrahes statusline but none for tabline . Not sure if lualone can do anything about this .

**Comment by shadmansaleh** [comment]
I was wrong there is `:redrawtabline` you could set a timmer that executes `:redrawtabline` to refreash it more frequently.

**Comment by mystilleef** [comment]
Thanks for the suggestion. For the benefit of new users, I put this in my vimrc. 

`au! InsertLeave,TextChanged,CursorMoved * silent! redrawtabline`

It's best practice to wrap that inside an `augroup`.

I don't know the performance implications of this. But for now, it works for me. 

Maybe this can be added to the FAQ?
