### ISSUE TITLE
Is it possible to only show first letter of current mode?

### ISSUE THREAD

**Issue by pesader** [hoob3rt/lualine.nvim#306]
Since I'm usually on a small screen, I'd like to save space on the statusline by displaying only the first letter of the current Vim Mode (i.e. 'N' for Normal Mode, 'I for Insert Mode, etc).

I suspect it may be possible to do to so using the `format` option. Has anyone been able to accomplish that?

Also, thanks hoob3rt and all contributors for developing this awesome plugin! My text editor has never been faster and prettier :)

**Comment by shadmansaleh** [comment]
```lua
lualine_a = {{'mode', format=function(mode) return mode:sub(1,1) end}
```

**Comment by pesader** [comment]
@shadmansaleh Works like a charm, thank you so much!

**Comment by TomRobinsonIO** [comment]
Is there a way to have this display the first letter of each word. e.g. Normal = N but Visual Block = VB?

**Comment by shadmansaleh** [comment]
@TomRobinsonIO  `fmt`  provides you all the flexibility you need.
You just have to implement the transformation as a lua function.
This will print first letters of every word
 ```lua
lualine_a = {
    {'mode', function (mode)
        return table.concat(vim.tbl_map(function (word) return word:sub(1,1) end, vim.split(mode, ' ')))
      end
    }
}
```
