### ISSUE TITLE
Bug: Authentication prompt and failed to install

### ISSUE THREAD

**Issue by barun108** [hoob3rt/lualine.nvim#312]
### Self Checks

- [x] I'm using the latest lualine and neovim nightly.
- [x] I didn't find the issue in exsisting issues or prs.

### Minimal config to reproduce the issue

<details>

I am trying to install lualine on Windows 10 machine, using  savq/paq-nvim plugin manager,
when I try to install, it opens a github authentication window, 
I tried authenticating using token and through browser , but it fails 
<summary>Config</summary>

</details>

**Comment by shadmansaleh** [comment]
Can you install other plugins ? It's a public repo if you're trying to clone over https you shouldn't require authentication .

**Comment by barun108** [comment]
My git settings are configured properly with ssh key
All other plugins are installing without any issue

Although after so many attempts  it installed 
I don't know what was the problem
I am closing this issue for time being 
Thanks
