### ISSUE TITLE
Feat: Option for component to be centred in lualine?

### ISSUE THREAD

**Issue by benfrain** [hoob3rt/lualine.nvim#313]
### Requested feature
The ability to place a component in a central area of the lualine (thinking filename)

### Motivation
At present there are two groups of information. However, I feel that, filename, in particular, would be easier to visually parse at a glance if central in the lualine. Typically that is the piece of information my eyes go to the status line for most.

**Comment by shadmansaleh** [comment]
You could do something like
```lua
lualine_c = {
    function() return '%=' end,
    'filename'
}
```

**Comment by benfrain** [comment]
@shadmansaleh  i did try that as I saw you advised something similar on another ticket, but when I do that I just don't see the filename at all

**Comment by shadmansaleh** [comment]
It works for me. Paste you're config ;)

**Comment by benfrain** [comment]
Thanks @shadmansaleh turns out it was an error between keyboard and chair ;) That works well. For future travellers, you can do it with multiple components like this:

```
    lualine_c = {
      {"diagnostics", sources = {"nvim_lsp"}},
      function()
        return "%="
      end,
      "filename"
    },

```
