### ISSUE TITLE
In inactive buffer lualine show filetype from active buffer

### ISSUE THREAD

**Issue by basilgood** [hoob3rt/lualine.nvim#32]
I have this config:
``` lua
local lualine = require('lualine')
lualine.sections = {
  lualine_a = { 'mode' },
  lualine_b = { 'filename' },
  lualine_x = { 'filetype' }
}

lualine.inactive_sections = {
  lualine_a = {  },
  lualine_b = { 'filename' },
  lualine_x = { 'filetype'  }
}
lualine.status()
```
I want lualine to show in the inactive buffer filetype and not progress.
With the above config shows filetype from active buffer.
If active buffer it's lua filetype and inactive buffer it's vim,
lualine in inactive buffer(which is vim filetype) shows lua filetype from active buffer.
vim-lightline shows this correctly.
Thank's for this beautiful plugin.

**Comment by hoob3rt** [comment]
Thank you for pointing that out, I will try to fix this soon :)

**Comment by hoob3rt** [comment]
Could you confirm if https://github.com/hoob3rt/lualine.nvim/commit/710d5ad8382f5f4773f2bdf1bab9c4b1967e74da solves this issue?

**Comment by basilgood** [comment]
Yes I confirm your last update solved this issue.
It works perfectly.
Thank you very much, very good job :)

**Comment by hoob3rt** [comment]
I noticed I created another bug with this, ouch, fixing it now.

**Comment by hoob3rt** [comment]
Should be all good now, thanks for your initial input :)

**Comment by basilgood** [comment]
Yes I saw the other bug but it's fixed now.

**Comment by megalithic** [comment]
I'm noticing this is happening again with latest. :( @hoob3rt

**Comment by ryantking** [comment]
I'm seeing something similar only with the filename. Changing windows seems to change the filename on both the current and previous windows. Currently on the latest version.

**Comment by shadmansaleh** [comment]
See if #97 fixes it for you

**Comment by ryantking** [comment]
@shadmansaleh Just about! When you first open a new window and switch files, the previous window's filename updates to the new file. After you switch to the previous window though the filenames all work as expected so around 95% fixed I suppose 🤷🏻

**Comment by shadmansaleh** [comment]
>95% fixed I suppose 🤷🏻

How about now?

**Comment by megalithic** [comment]
Fixed for me! Thanks team!

**Comment by ryantking** [comment]
@shadmansaleh All good, thanks for the fix!

**Comment by hoob3rt** [comment]
My bad for not testing the new implementation, sorry. And thank you @shadmansaleh for providing a quick fix

**Comment by megalithic** [comment]
> My bad for not testing the new implementation, sorry. And thank you @shadmansaleh for providing a quick fix

No apology necessary! Hope you did well on your exams!
