### ISSUE TITLE
[Question] Where do I include my custom theme file?

### ISSUE THREAD

**Issue by paniash** [hoob3rt/lualine.nvim#321]
Hi!

Firstly, thanks for the wonderful plugin, it's much faster than the vimscript alternatives. I was wondering where I need to include my custom theme file for lualine. I'd appreciate any help. Thanks! 😃

**Comment by shadmansaleh** [comment]
You'll have to put it in `&rtp/lua/lualine/themes/`

If you're putting it in your configs that means at `~/.config/nvim/lua/lualine/themes/`

**Comment by paniash** [comment]
I tried that and included my custom file in `~/.config/nvim/lua/lualine/themes/dark.lua` and added `{options = {theme = dark}}`, but end up with the error message, 

```
theme dark not found, defaulting to gruvbox
```

**Comment by shadmansaleh** [comment]
You're on linux right ?

Can you check what does running this say ?
```vim
:echom stdpath('config')
```
If stdpath('config') isn't `~/.config/nvim`  you need to change that part with the result from stdpath . Other wise it looks correct . Not sure why it won't work.

**Comment by paniash** [comment]
> ```viml
> :echom stdpath('config')
> ```

I do get `~/.config/nvim` as the output.

> Also see if
> 
> ```lua
> :lua print(vim.inspect(require'lualine.themes.dark')))
> ```

I get the following output:
```
E5108: Error executing lua vim.lua:63: /home/ashish/.config/nvim/lua/lualine/themes/dark.lua:45: '<eof>' expected near 'require'
```

**Comment by shadmansaleh** [comment]
delete the last line
```lua
require('lualine').setup {options = {theme = dark}}
```

**Comment by paniash** [comment]
Thank you!
