### ISSUE TITLE
Feat: Curved borders for outer edges of status line

### ISSUE THREAD

**Issue by lokesh-krishna** [hoob3rt/lualine.nvim#324]
### Requested feature
Is it possible to have curved borders for the outer edges of the status line? Something like what [neoline](https://github.com/adelarsq/neoline.vim) does here:

<img width="1237" alt="115162411-c4500e80-a079-11eb-8315-7b1d30265e3a" src="https://user-images.githubusercontent.com/20235646/131241211-5f7acdb4-133b-47a3-8c05-48f71852bcd7.png">

Referring to the extreme left and right of the bar here as we can use component separators to get curved borders on the inside of the bar

My bar for reference where the left and right edges are straight and couldn't find anything in the documentation that suggested I could change it to be curved. 
![image](https://user-images.githubusercontent.com/20235646/131241242-f0811fd1-94d8-4929-8832-b4ba608ec84e.png)

### Motivation
Lualine offers excellent customisability that's simple to setup. Would be nice if this were implemented in the form of setting the leftmost and rightmost characters of the bar to let users have even greater control over the look of the bar.

**Comment by shadmansaleh** [comment]
Grab [shadmansaleh](https://github.com/shadmansaleh/lualine.nvim) . There you can set both left and right transitional separators on component basis with `separator` option. https://github.com/shadmansaleh/lualine.nvim#component-options

**Comment by lokesh-krishna** [comment]
Trying your fork and have this in my `init.vim` but it doesn't seem to be taking effect. Am I missing something?

```
  sections = {
    lualine_a = {
	    {
	    'mode',
	    separator = {'', ''},
	    }
	    },
    lualine_b = {'filename', 'branch'},
    lualine_c = {},
    lualine_x = {'filetype'},
    lualine_y = {'progress'},
    lualine_z = {'location'}
  },
```

Also not sure about how to color those separators from the help text you've provided for colors  🙈

**Comment by shadmansaleh** [comment]
>Ryans Software

You need to have `color` option too .

**Comment by lokesh-krishna** [comment]
Adding color does change the color of the component but the left separator still doesn't take effect.

With this in my config:
```
lua << EOF
require("lualine").setup {
  options = {
    icons_enabled = true,
    theme = 'moonfly',
    component_separators = {'', ''},
    section_separators = {'', ''},
    disabled_filetypes = {},
    extensions = {'nvim-tree'}
  },
  sections = {
    lualine_a = {
	    {
	    'mode',
	    separator = {'', ''},
	    color = {fg = '#88c0d0', bg = 'bf616a'}
	    }
	    },
    lualine_b = {'filename', 'branch'},
    lualine_c = {},
    lualine_x = {'filetype'},
    lualine_y = {'progress'},
    lualine_z = {'location'}
  },
  inactive_sections = {
    lualine_a = {},
    lualine_b = {},
    lualine_c = {'filename'},
    lualine_x = {'location'},
    lualine_y = {},
    lualine_z = {}
  },
  tabline = {},
  extensions = {}
}
EOF
```
I still get the following as my bar instead of a rounded border for the left margin of component A. 

![image](https://user-images.githubusercontent.com/20235646/131246726-1c42b06d-e884-47ba-a14f-b9e1fe6b78f8.png)

**Comment by shadmansaleh** [comment]
try putting a component then returns a space . Because that's the first component there's no component on it's left to apply transional separator

```lua
lua << EOF
local empty = {function() return ' ' end,
    padding = 0,
    color = 'lualine_c_normal',
}
require("lualine").setup {
....
  sections = {
     lualine_a = { empty,
          {'mode',
	    separator = {'', ''},
	    color = {fg = '#88c0d0', bg = 'bf616a'}
	    }
     }
....
}
EOF
```

**Comment by shadmansaleh** [comment]
Forget about my previous comment . Just update lualine . with this commit https://github.com/shadmansaleh/lualine.nvim/commit/bae19db8d0a49bb1329317826d1ceb70bb22210a .

This will work
```lua
lua << EOF
require("lualine").setup {
  options = {
    icons_enabled = true,
    theme = 'moonfly',
    component_separators = {'', ''},
    section_separators = {'', ''},
    disabled_filetypes = {},
    extensions = {'nvim-tree'}
  },
  sections = {
    lualine_a = {{'mode', separator = {'', ''}}},
    lualine_b = {'filename', 'branch'},
    lualine_c = {},
    lualine_x = {'filetype'},
    lualine_y = {'progress'},
    lualine_z = {{'location', separator = {'', ''}}}
  },
  inactive_sections = {
    lualine_a = {},
    lualine_b = {},
    lualine_c = {'filename'},
    lualine_x = {'location'},
    lualine_y = {},
    lualine_z = {}
  },
  tabline = {},
  extensions = {}
}
EOF
```

**Comment by lokesh-krishna** [comment]
![image](https://user-images.githubusercontent.com/20235646/131251394-7c15f722-fec4-445e-9b1c-07b997ba23ed.png)

Thank you so much! I was finally able to realize the look I was going for! :D

Just one small question, is it possible to set the background of just the separator so that it blends in with neovim's background instead of it picking colors from the adjacent component? 

Presently, the color picked from the adjacent component shows up at the very edges of the bar and while it's barely noticeable and is certainly nitpicking, I just wanted to know if that's a possibility. 

Once again, thanks a lot for helping me through this. Made my day! :D

**Comment by shadmansaleh** [comment]
> Just one small question, is it possible to set the background of just the separator so that it blends in with neovim's background instead of it picking colors from the adjacent component?

You can try putting an empty component in the front and in the end with `Normal` hl . So lualine picks up color from that.

```lua
local empty = {function() return ' ' end,
    padding = 0,
    color = 'Normal',
}
require("lualine").setup {
....
  sections = {
     lualine_a = { empty,
          {empty, 'mode',
	    separator = {'', ''},
	    color = {fg = '#88c0d0', bg = 'bf616a'},
            left_padding = 0,
	    }
     }
....
}
```

> Just one small question, is it possible to set the background of just the separator so that it blends in with neovim's background instead of it picking colors from the adjacent component?

I intentionally didn't allow users to directly specify separator colors like galaxyline . Because firstly it's complicated for users to maintain all those colors . More importantly it's hard for users to handle separator colors dynamically . Like galaxyline allows you to set colors directly it's cool as long as all the components are displayed . Once a component disappears you're in trouble as separators will have wrong colors.

**Comment by shadmansaleh** [comment]
Also once you're done If you don't mind I'd like provide your config as example.

I was thinking about providing an example of using custom separators on components . Your screenshot 💯 looks nice .

I'd really appreciate if you make a pr :) You'll just have to put the config in a file in [examples](https://github.com/shadmansaleh/lualine.nvim/tree/master/examples) and a screenshot in [screenshots](https://github.com/shadmansaleh/lualine.nvim#screenshots) section like evilline. But all that only if you want to share it 😄

**Comment by lokesh-krishna** [comment]
I'd be honored to :D
