### ISSUE TITLE
Feat: Support for Paste mode

### ISSUE THREAD

**Issue by knmac** [hoob3rt/lualine.nvim#325]
### Requested feature

Could you please add support to show the paste mode, i.e., via the command `set paste`.

### Motivation

Other plugins such as "airline" or "lightline" support this feature. It helps indicate the current paste status so that I don't mess up the indentation (due to `autoindent`) when I try to paste some code from the internet.

Thank you!

**Comment by shadmansaleh** [comment]
Paste mode is deprecated in neovim  . No reason to support it. check `:h 'paste'`

**Comment by knmac** [comment]
Oh, thank you!

**Comment by Grazfather** [comment]
Tracked this through another issue: Paste mode still does work, and is needed if what you're pasting from doesn't know to use bracketed paste mode.
