### ISSUE TITLE
Bug: Quickfix extension throws errors on usage of quickfix window 

### ISSUE THREAD

**Issue by milkias17** [hoob3rt/lualine.nvim#327]
### Self Checks

- [x ] I'm using the latest lualine and neovim nightly.
- [ x] I didn't find the issue in exsisting issues or prs.

### How to reproduce the problem
Just populate the quickfix window, example do :vim {pattern} in your project
### Actual behaviour
After opening the quickfix window, any operation like :cnext, :cprev, or even :cclose spit out this error:
`Error detected while processing BufLeave Autocommands for "*":                                                                                                 
E5108: Error executing lua [string ":lua"]:1: E539: Illegal character < >                                                                                      
Error detected while processing WinLeave Autocommands for "*":                                                                                                 
E5108: Error executing lua [string ":lua"]:1: E539: Illegal character < > `

This is my config for lualine for this error to happen:
`require('lualine').setup{
    options = {
        theme = 'onedark',
        section_separators = {'', ''},
        component_separators = {'', ''}
    },
    sections = {
        lualine_a = {'mode'},
        lualine_b = {'branch'},
        lualine_c = {
            {
                'filename',
                file_status = true,
                path = 1
            },
            {
                'diagnostics',
                sources = {'nvim_lsp'},
            }
        },
        lualine_x = {'filetype'}
    },
    extensions = {'quickfix', 'nvim-tree', 'fzf'}
}`

**Comment by shadmansaleh** [comment]
Can you reproduce this on [shadmansaleh/lualine.nvim](https://github.com/shadmansaleh/lualine.nvim) ?

**Comment by milkias17** [comment]
Wow thanks your fork fixes the issue.
