### ISSUE TITLE
Feat: Word Count component

### ISSUE THREAD

**Issue by benfrain** [hoob3rt/lualine.nvim#328]
### Requested feature
Help with getting a word count displaying for txt/md files.

### Motivation
I'd like a word count as I type for text based files.

Starting simple, and ignoring file types, following the docs I thought I could do this:

```
local function getWords()
  return vim.fn.wordcount().words
end
```
And then use that in my Lualine config like this:

```
    lualine_c = {
      { "diagnostics", sources = { "nvim_lsp" } },
      function()
        return "%="
      end,
      "filename",
      { getWords },
    },
```

But that doesn't seem to work. This is 100% likely due to my ineptitude but any pointers appreciated!

**Comment by shadmansaleh** [comment]
try 
```lua
local function getWords()
  return tostring(vim.fn.wordcount().words)
end
```

**Comment by benfrain** [comment]
Simple as that - Thanks!

**Comment by SmashMineGame** [comment]
Is there a way to make this show the wordcount of the selected region when some text is selected like in visual mode?

**Comment by benfrain** [comment]
My complete function will do that. I have it set to only appear for certain file types but you should be able to amend to your needs:

```lua
local function getWords()
  if vim.bo.filetype == "md" or vim.bo.filetype == "txt" or vim.bo.filetype == "markdown" then
    if vim.fn.wordcount().visual_words == 1 then
      return tostring(vim.fn.wordcount().visual_words) .. " word"
    elseif not (vim.fn.wordcount().visual_words == nil) then
      return tostring(vim.fn.wordcount().visual_words) .. " words"
    else
      return tostring(vim.fn.wordcount().words) .. " words"
    end
  else
    return ""
  end
end
```

Disclaimer: I'm a Lua noob, not sure how solid that code is!
