### ISSUE TITLE
Current char hex code in statusline

### ISSUE THREAD

**Issue by cpkio** [hoob3rt/lualine.nvim#329]
Can you add current character under cursor hex as a component (like `0x2014`)? I would gladly write this myself but I dont yet understand how to do it in Lua.

**Comment by shadmansaleh** [comment]
> I dont yet understand how to do it in Lua
You don't need to just use '%B'.

https://github.com/shadmansaleh/lualine.nvim#vims-statusline-items-as-lualine-component

**Comment by cpkio** [comment]
Note of this `sections = {lualine_c = {'%=', '%t%m', '%3p'}}` or this `sections = {lualine_c = {"os.data('%a')", 'data'}}` output anything on on my system.

**Comment by shadmansaleh** [comment]
Did you install [shadmansaleh/lualine.nvim](https://github.com/shadmansaleh/lualine.nvim) ?

**Comment by shadmansaleh** [comment]
What's your entire config ?

**Comment by cpkio** [comment]
```
require('lualine').setup({ sections = {
		lualine_a = { {'mode', lower = false} },
		lualine_b = { 'branch' },
		lualine_c = { vim.fn.getcwd, {'filename', color = "PmenuSelBold"} },
	},
})
```

**Comment by shadmansaleh** [comment]
getcwd expects different arguments then what's given to lualines function components.

Lualines function conponents get somthing like
`function(self, is_active)` so when lualine calls getcwd with those it errors out . You should wrap it witha  function to ignore the args or pass it as a function name

```lua
lualine_c = {function() return vim.fn.getcwd() end}
```
or 
```lua
lualine_c = {'getcwd'}
```

Try:
require('lualine').setup({ sections = {
		lualine_a = { {'mode', lower = false} },
		lualine_b = { 'branch' },
		lualine_c = { 'getcwd', {'filename', color = "PmenuSelBold"}, '%B' },
	},
})

**Comment by cpkio** [comment]
`'%B'` is not shown anyway.

**Comment by shadmansaleh** [comment]
Is your cursor on a char ?

**Comment by cpkio** [comment]
Of course it is 🤷‍♂️

**Comment by shadmansaleh** [comment]
Can you give a screenshot ?

**Comment by cpkio** [comment]
`Error executing lua [string ":lua"]:1: attempt to call field 'get_config' (a nil value)`. There's no such function?

![2021-09-02_181546](https://user-images.githubusercontent.com/1917113/131870889-1ef7ebbe-7e99-44c2-862d-ab5645cbcf52.png)
![2021-09-02_181606](https://user-images.githubusercontent.com/1917113/131870807-d306b2b3-dec0-4e9c-9f30-a2d1df59dea1.png)

**Comment by shadmansaleh** [comment]
You have `hoob3rt/lualine.nvim` installed not `shadmansaleh/lualine.nvim` .

**Comment by cpkio** [comment]
Your fork didn't load, so I had to revert to original:
`Error detected while processing C:\NvimLua\nvim\init.lua:
E5113: Error while calling lua chunk: ...ata\site\pack\user\start\lualine.nvim\lua\lualine.lua:256: attempt to index field 'config_module' (a number value)`

**Comment by shadmansaleh** [comment]
Use [this](https://gist.github.com/shadmansaleh/3aca29632e9a77a632705b62617c9dac) and try to reproduce the crash without any other plugins influence.

**Comment by cpkio** [comment]
I'm on Windows so I cannot use bash script. I've created an isolated installation by creating separate `nvim` and `nvim-data...` directories and setting the `XDG_*` variables. Strangely enough, now your plugin works (it still cannot do stuff like `0x%B` for `0x2014` for example, but anyway…). And I only had a few plugins installed to get this problem. Will try finding out what plugin is intervening with yours.

**Comment by cpkio** [comment]
Yes. Renaming it doesn't seem to help.

**Comment by shadmansaleh** [comment]
What did you rename it to ?

**Comment by cpkio** [comment]
Sorry, renamed the wrong one. Now its working. Thanks for your efforts! 👍

I found that 'mode` separator tends to disappear when lualine elements are colored via highlight groups.
