### ISSUE TITLE
Bug: Can't get lsp-status.nvim to work with lualine

### ISSUE THREAD

**Issue by Hubro** [hoob3rt/lualine.nvim#333]
### Self Checks

- [x] I'm using the latest lualine and neovim nightly.
- [x] I didn't find the issue in exsisting issues or prs.

### How to reproduce the problem

My config:

```lua
  use {
    -- "hoob3rt/lualine.nvim",

    -- Fork that allows reloading config. See: https://github.com/hoob3rt/lualine.nvim/pull/311
    --
    "shadmansaleh/lualine.nvim",

    requires = { "nvim-lua/lsp-status.nvim" },
    config = function()
      require("lsp-status").config {}

      _G.setup_lualine = function(options)
        options = options or {}

        default_options = {
          tabline = {
            lualine_a = { "filename" },
            lualine_b = { require"lsp-status".status }
          }
        }

        final_options = vim.tbl_deep_extend("force", default_options, options)

        print("Setting up lualine with options: " .. vim.inspect(final_options))

        require("lualine").setup(
          vim.tbl_extend("force", default_options, options)
        )
      end

      setup_lualine()
    end
  }
```

(I need the global setup function to be able to switch color scheme later - it's currently not possible to change scheme without setting up lualine from scratch)

When I run nvim I get the message:

```
Setting up lualine with options: {
  tabline = {
    lualine_a = { "filename" },
    lualine_b = { <function 1> },
    <metatable> = {
      __tostring = <function 2>
    }
  }
}
```

So it's being set up with the correct options.

### Actual behaviour

I only see the filename in the tabline, I don't see any output from "lsp-status.nvim":

![image](https://user-images.githubusercontent.com/597206/132223444-87ba41db-4b68-4983-85e8-8760b9d9a7fb.png)

But if I run the status function directly and print the output:

![image](https://user-images.githubusercontent.com/597206/132223513-d3c8a73b-ed26-43d5-a4b9-76c04c6afaef.png)

![image](https://user-images.githubusercontent.com/597206/132223516-101101a7-0e8d-4db4-a55b-60cac7284fe7.png)

It's producing text, so why isn't it being displayed in the tabline? :confused: 

### Expected behaviour

I would expect the lsp-status text to be displayed in the tabline.

### Aditional information

```
➜ nvim --version
NVIM v0.5.0
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim/src/neovim-0.5.0/build/config -I/build/neovim/src/neovim-0.5.0/src -I/usr/include -I/build/neovim/src/neovim-0.5.0/build/src/nvim/auto -I/build/neovim/src/neovim-0.5.0/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

Freshly updated packages using packer.nvim.

### Minimal config to reproduce the issue

(See above)

**Comment by shadmansaleh** [comment]
1. wrap the lsp status function with a function to discard arguments provided by lualine
```lua
lualine_b = { function() return require"lsp-status".status() end }
```

The function signature for function components is
```lua
function(self, is_active)
```

while function signature for lsp_status is
```
function(bufnr)
```
So it doesn't work if you just give the function is lsp-status case.

Also tabline is updated really rarely by default in (neo)vim . To force an update at anytime you can run `:redrawtabline` if you're displaying anything that requires quick refresh I'd suggest setup a timer that calls the command periodically. 

> I need the global setup function to be able to switch color scheme later - it's currently not possible to change scheme

It is on myfork you can set the theme to `auto` and lualine will change it's theme as you change colorscheme with `:colorscheme`  command.

You can just change the theme too .
like
```lua
:lua require'lualine'.setup{options = {theme = 'gruvbox'}}
```
running that command will just change the theme to gruvbox.

Also there's easier way to setup from previous config.

```lua
require'lualine'.get_config()
```
will return currently active config . All these are in my fork though not here.

**Comment by Hubro** [comment]
@shadmansaleh Oh damn, that's all insanely helpful information! I was pretty sure my usage was correct since I copied it directly from the lualine README :smile: 

![image](https://user-images.githubusercontent.com/597206/132250715-7a04f067-cc98-4a48-8c75-ebcf2aef05f1.png)

I will try the method you suggested to change colorschemes, thanks!
