### ISSUE TITLE
Solarized Dark theme not working in Alacritty 

### ISSUE THREAD

**Issue by ex4722** [hoob3rt/lualine.nvim#336]
Recently installed Lualine and found a really cool config online and borrowed parts of it. Part of this is that the themes used is solarized_dark. While rendering this theme it's colors seem to be a little off. 

I'm not really sure whats going on so as I had had a issue with solarized before but I ended up using a script provided by a vim solarized theme at https://github.com/lifepillar/vim-solarized8/blob/master/scripts/solarized8.sh. 

As of my environment varibles $COLORTERM is truecolor, $TERM is screen and the $SHELL is /usr/bin/zsh.  

![image](https://user-images.githubusercontent.com/77011982/132903956-6929e30e-d843-4b8f-a717-8169b99abcd8.png)

Any ideas on what I can do?

**Comment by shadmansaleh** [comment]
Do you have `termguicolors` set ?

Can you share your lualine config ?

You can customize a theme in your config like shown in [customizing themes section](https://github.com/shadmansaleh/lualine.nvim#setting-a-theme).

**Comment by ex4722** [comment]
Sorry for wasting your time. Turns out my issue is still with my the way that tmux changed certain variables and changing them caused it to work just fine. For anyone with a simular issue be sure to set `set -g default-terminal "screen-256color"`  to get tmux to not change the defaults.
