### ISSUE TITLE
add support for lightline colorschemes

### ISSUE THREAD

**Issue by hoob3rt** [hoob3rt/lualine.nvim#34]
As mentioned [here](https://github.com/nvim-lua/wishlist/issues/3#issue-679063591), having the ability to use `lightline`'s colorschemes would be a nice feature to have.

**Comment by shadmansaleh** [comment]
I think they will have to be ported . Those colprscemes are written in vimscript you are oviously not hoping to interprete them...

**Comment by hoob3rt** [comment]
> t you are oviously not hoping to interprete them...

Yeah obviously not. The themes in lightline's main repo should and will be ported. This issue's aim is to discuss the possibility of using lightline's highlight groups in lualine. 

The gruvbox theme I am using comes with both airline and lightline themes supplied, it would be great to have support for them.

But keep in mind this thread is for discussion only, I should remove the help wanted label.

Using lightline colorschemes will be redundant when https://github.com/hoob3rt/lualine.nvim/pull/26 is implemented correctly.

**Comment by coxackie** [comment]
Do you mean that after #26 in implemented, there will be no colour schemes any more? Or will they be optional? My opinion is that, if #26 is actually successful, colour schemes should be dropped. This will relieve future maintenance significantly.

**Comment by shadmansaleh** [comment]
>My opinion is that, if #26 is actually successful, colour schemes should be dropped.

I donn't think it should be droped . I shouldn't be forced to use same colorscheme on both editor and statusline . I should be able to chose separately.

Also I don't think themes require much maintanace .

**Comment by coxackie** [comment]
perfectly fine also, just make sure there is an option if we want to opt in matching the colorscheme on editor and statusline. I personally like the consistency that it would bring, but understandably there will be others that like more variety.

**Comment by hoob3rt** [comment]
> perfectly fine also, just make sure there is an option if we want to opt in matching the colorscheme on editor and statusline. I personally like the consistency that it would bring, but understandably there will be others that like more variety.

Yes there will be. I think providing some popular themes out of the box is nice but you will also be able to set `theme=auto` to keep things easy and consistent

**Comment by shadmansaleh** [comment]
### lightline to lualine theme converter
[link](https://gist.github.com/shadmansaleh/000871c9a608a012721c6acc6d7a19b9)

Open the file in vim with lightline installed. Just change the theme name on top . And run :luafile %
you will have theme_name.lua file on you directory with the theme .

**Comment by hoob3rt** [comment]
@shadmansaleh the link and usage to your theme converter should be in the readme imo

**Comment by shadmansaleh** [comment]
> the link and usage to your theme converter should be in the readme imo

Ha ha . I had written it as a throwaway script when I was conberting themes. As it was doing a pretty good job I shared it as a gist so it might be helpful if someone else is converting themes . When I was writting it I had no intention of sharing it . So it's horrible to look at . If you want to put it in README.md you can . The gist has uses instructions . So putting the link should be enough . Maybe in contributing.md insted of README.md.
