### ISSUE TITLE
Installation / Setup Issue

### ISSUE THREAD

**Issue by MaRo99382** [hoob3rt/lualine.nvim#344]
I'm a newbie to neovim and trying to setup lualine as my statusline plugin.
My init.vim looks like this:
I use vim-plug to install the plugin.
![init vim_1](https://user-images.githubusercontent.com/80778765/134803440-1cad5047-84a8-41cc-a2c6-881ef01dd7fb.png)
Then I use the standard setup.
![init vim_2](https://user-images.githubusercontent.com/80778765/134803469-8934f214-6949-4926-a477-24e1249844ac.png)

When I then start neovim it shows the following error:
![lualine_error_message](https://user-images.githubusercontent.com/80778765/134803485-903c5c94-5753-4e58-9bfe-831c9b32c09f.png)

Can someone help me with this issue?
Since no one else has this problem, I assume it is just a stupid mistake by me regarding the setup of neovim and/or lualine.

**Comment by shadmansaleh** [comment]
Use [shadmansaleh/lualine.nvim](https://github.com/shadmansaleh/lualine.nvim)

This repo is currently not maintained . See #311

**Comment by MaRo99382** [comment]
Hi shadmansleh,

I appreciate your answer!
I now deleted the old hoob3rt repo that was installed by vim-plug and replaced it with your 'shadmansaleh/lualine.vim' and let vim-plug install that.
But the error still occurs, even though now in a different line in the init.lua file in the repo.
My init.vim:

![init_vim](https://user-images.githubusercontent.com/80778765/134812014-3232ea9d-9b46-4790-8576-c1362b732c99.png)

The error when I start neovim:


![lualine_error](https://user-images.githubusercontent.com/80778765/134812020-7ee83eb9-6af8-4df1-aa72-23613ba1fb8f.png)

Can you help with that?

**Comment by shadmansaleh** [comment]
Let me guess you are not in neovim 0.5 . lualine only supports version 0.5 or higher.

**Comment by MaRo99382** [comment]
You're absolutely right.
Installed it using the apt package manager, which does not seem to have the recent nvim version available.
I installed the 0.5 version using snap now and it works.
Sorry for this. Appreciate you're work!
