### ISSUE TITLE
[Question] Set inactive_sections for extensions

### ISSUE THREAD

**Issue by eeeXun** [hoob3rt/lualine.nvim#347]
I use `extensions` to set for different filetype. The setting of `sections` work properly. But the `inactive_sections` seems not take effect. It just the same as `sections`.

Here is my setting.
```lua
local function line()
    return vim.fn.line(".")
end

local function col()
    return vim.fn.col(".")
end

local function lines()
    return vim.fn.line("$")
end

local function progress() 
    return string.format("%2d%%%%", 100 * line() / lines())
end

local function localtion()
    return string.format(" %d/%d : %d", line(), lines(), col())
end

local function wordcounts()
    return string.format("%d W", vim.fn.wordcount().words)
end

local text_extension = {
    filetypes = {"text"},
    sections = {
        lualine_a = {"mode"},
        lualine_b = {"filename"},
        lualine_c = {"branch", "diff"},
        lualine_x = {wordcounts},
        lualine_y = {"filetype"},
        lualine_z = {progress, localtion}
    },
    inactive_sections = {
        lualine_a = {},
        lualine_b = {},
        lualine_c = {"filename"},
        lualine_x = {progress},
        lualine_y = {localtion},
        lualine_z = {}
    },
}

require("lualine").setup{
    extensions = {text_extension}
}
```

**Comment by shadmansaleh** [comment]
Use [shadmansaleh/lualine.nvim](https://github.com/shadmansaleh/lualine.nvim)

[hoob3rt/lualine.nvim](https://github.com/hoob3rt/lualine.nvim) is currently not maintained . See https://github.com/hoob3rt/lualine.nvim/pull/311

Inactive section will work there.

Also you can use builtin stl placeholders directly there .
So instead of

```lua
lualine_z = {progress, localtion}
```
you can just do
```
lualine_z = {'%2p%%', ' %l/%L : %c'}
```

**Comment by eeeXun** [comment]
Thanks a lot.

**Comment by eeeXun** [comment]
I found that if I use builtin stl placeholders, I can't prefix with other character.
So the `' %l/%L : %c'` would not render correctly. What I can do is
```lua
lualine_z = {'%2p%%  %l/%L : %c'}
```
Is that a bug?

**Comment by shadmansaleh** [comment]
Ohh right . It recognizes a string is a stl placeholder based on whether it starts with `%` or not . Instead of releying on type inference you can specify the type with `type` option. So

This would work:
```lua
lualine_z = {'%2p%%', {' %l/%L : %c', type='stl'}}
```

Also you can use the icon option to set icon (prefix a compponent)

This should work too.
```lua
lualine_z = {'%2p%%', {'%l/%L : %c', icon=''}}
```
