### ISSUE TITLE
Git branch persists even after buffer change

### ISSUE THREAD

**Issue by coxackie** [hoob3rt/lualine.nvim#37]
Suppose I open a buffer and the file is at a git folder. The branch is displayed, which is good.

 Now, I switch to another buffer with a file at another folder that is not (and neither its parents are) git-controlled. The git branch from the previous buffer will persist on the status line for the new buffer. Even if I close the previous buffer, the git branch persists.

 Not sure what the issue is; maybe something about async?

**Comment by hoob3rt** [comment]
Nice catch, this is also an issue with the `signify` component but I think these are two different bugs, I will try to fix this tomorrow.

**Comment by hoob3rt** [comment]
Should be  fixed :)

**Comment by coxackie** [comment]
thanks, looks good, indeed. If there is any issue, I will report.
