### ISSUE TITLE
Changing the colorscheme at runtime also effects lualine's colors

### ISSUE THREAD

**Issue by bool3max** [hoob3rt/lualine.nvim#4]
Changing the colorscheme at runtime using `:colorscheme <scheme>` also alters lualine's own colors, even though it's set to `gruvbox` in the config. 

This does not occur, for example, with `vim-airline` when `g:airline_theme` is set in the config.

**Comment by hoob3rt** [comment]
Nice catch! This is definitely and unwanted behavior, I will look into it

**Comment by hoob3rt** [comment]
resolved with https://github.com/hoob3rt/lualine.nvim/commit/3ab706671898746c268f59ca7f02a4919072690f
