### ISSUE TITLE
additional setting for components

### ISSUE THREAD

**Issue by hoob3rt** [hoob3rt/lualine.nvim#45]
as mentioned in https://github.com/hoob3rt/lualine.nvim/issues/16#issuecomment-753699274 there should be additional settings for lualine's components. Something like

* icon
* padding
* uppercase/lowercase

Let me know if you wish to have anything else supported.

**Comment by deevus** [comment]
Full path for `filename` component would be appreciated. I've found myself missing that.

**Comment by bobicino** [comment]
For full file path, it would be great if it had an option to use `pathshorten` if the window size get lower than a defined value.
This is what I have been using so far:
```
local function filepath()
  local path = vim.fn.expand('%')
  if vim.fn.empty(path) == 1 then return '' end
  local squeeze_width  = vim.fn.winwidth(0) / 2
  if squeeze_width <= 42 then
    path = vim.fn.pathshorten(path)
  end
  return path
end
lualine.sections.lualine_c = { filepath }
```

**Comment by shadmansaleh** [comment]
>For full file path, it would be great if it had an option to use pathshorten if the window size get lower than a defined value.-

good idea i'll add it to #60. Maybe we should see the lenght of file path too for shorting it .
By the way should we have relative filepath or complete filepath from root for full filename . What do you guys think?

**Comment by bobicino** [comment]
I have always used relative path. I find it more convenient since you are, in most cases, working in a project folder (maybe even set with `vim-rooter`).
But since we are discussing about options, it would be cool having both.. the only difference would be `expand('%:p')` instead of `expand('%')`.
Also looking for the string lenght is a great idea! 😊

**Comment by shadmansaleh** [comment]
>But since we are discussing about options, it would be cool having both.. the only difference would be expand('%:p') instead of expand('%')

I've added a relative option that can be set to false to have full_path from root otherwise it will show relative path . Also added path shortning.

**Comment by mellery451** [comment]
I tried making sense of the comments/links here, but can't quite follow. What's the best way currently to display a root-relative filepath instead of just filename?
