### ISSUE TITLE
Branch doesn't show anything on detached head state

### ISSUE THREAD

**Issue by shadmansaleh** [hoob3rt/lualine.nvim#67]
As The title says. If you're on detached head state branch component is empty . I think it should show the commit id.

**Comment by hoob3rt** [comment]
this might be tricky since `git branch --show-current` has 0 exit code and no stdout in detached head state

**Comment by shadmansaleh** [comment]
>this might be tricky since git branch --show-current has 0 exit code and no stdout in detached head state

Yep also I donn't think we can use empty output as a idicator . I think the async code returns empty output all the time . right?

**Comment by shadmansaleh** [comment]
I think we can read .git/HEAD .

**Comment by hoob3rt** [comment]
Yes this would be a better solution. I made the branch component use git commands for mvp. There is still room for improvements

**Comment by shadmansaleh** [comment]
I'll create a pr when I implements it with .git/HEAD  . I donn't think it should be hard.
 go back to to find .git folder -> read .git/HEAD

Any idea on what exceptions we should handle?

**Comment by shadmansaleh** [comment]
It's done
