### ISSUE TITLE
cpu consuming

### ISSUE THREAD

**Issue by basilgood** [hoob3rt/lualine.nvim#76]
![image](https://user-images.githubusercontent.com/16057481/105181048-fb268f00-5b33-11eb-8cf9-c0110c4f992b.png)

With lualine neovim is in top 5 cpu consumers.

**Comment by shadmansaleh** [comment]
I thought it was fixed.

**Comment by hoob3rt** [comment]
I cannot reproduce this on my machine. Obviously the cpu usage spikes on buffer load but that happens even without lualine installed due to all the underlying autocommands.

**Comment by basilgood** [comment]
Yes you're right it's my fault.
I reinstalled the plugin and everything works perfectly.
The branch changes on rebase perfectly without nvim focus and the CPU is quiet.
I apologize for not paying attention to the plugin installation. 
You did a very good job.
