### ISSUE TITLE
lualine_diagnostics section?

### ISSUE THREAD

**Issue by pianocomposer321** [hoob3rt/lualine.nvim#77]
snippet from my lualine config file:

```lua
local M = {}

local function diagnostics()
...
end

function M.config()
    lualine.sections['lualine_diagnostics'] = { diagnostics }
    lualine.status()
end

return M
```

but nothing changes in my status line. If I set a different sections to my diagnostics function, it works as expected. But nothing shows when I set the `lualine_diagnostics` section.

**Comment by hoob3rt** [comment]
There is no diagnostics section as of right now. I will work on this when #60 is merged.

**Comment by pianocomposer321** [comment]
OK. For now then, how do I get colors set up (red for errors and orange/yellow for warnings)? Currently, this is how it looks:
![image](https://user-images.githubusercontent.com/54072354/105412745-bf0a3180-5bfa-11eb-85ba-12b67c810d82.png)

**Comment by pianocomposer321** [comment]
Also, if it's not implemented yet, should it be taken out of the README.md?

**Comment by hoob3rt** [comment]
Św

> Also, if it's not implemented yet, should it be taken out of the README.md?

Yea it should, thanks for pointing that out

**Comment by hoob3rt** [comment]
> OK. For now then, how do I get colors set up (red for errors and orange/yellow for warnings)? Currently, this is how it looks:
> ![image](https://user-images.githubusercontent.com/54072354/105412745-bf0a3180-5bfa-11eb-85ba-12b67c810d82.png)

try
```
:set stastusline = %#LineNr#
```
Etc

**Comment by pianocomposer321** [comment]
> > OK. For now then, how do I get colors set up (red for errors and orange/yellow for warnings)? Currently, this is how it looks:
> > ![image](https://user-images.githubusercontent.com/54072354/105412745-bf0a3180-5bfa-11eb-85ba-12b67c810d82.png)
> 
> try
> 
> ```
> :set stastusline = %#LineNr#
> ```
> 
> Etc

I'm sorry, I don't follow...that command results in an error.

Could you give a more complete example?

**Comment by pianocomposer321** [comment]
In case it's relevant, the way I have it set up is that the format is "E [errors in current buffer]:[total errors] W [warnings in current buffer]:[total warnings]"

**Comment by shadmansaleh** [comment]
>set stastusline = %#LineNr#

you are getting error because set command cann't have spaces . 
Can you provide the function you are using to provide the diagnostics . Theb I'll be able to further help you . for now it will be abit complecated . oncce #54 and #61 are merged life will be alot easier to create this kind of components .Also lualine will provide a diagnostic api itself . Not rewuireing to hack it yourself :)

**Comment by hoob3rt** [comment]
@shadmansaleh how is #54 relevant here? I think it's already merged.

Regarding the diagnostic api, I will work on it when we manage to perfect #60 and #61 . This will happen sooner than later

**Comment by shadmansaleh** [comment]
> how is #54 relevant here? I think it's already merged.

My bad I've tagged a wrong pr.

**Comment by pianocomposer321** [comment]
> Can you provide the function you are using to provide the diagnostics . Then I'll be able to further help you .

Sure, the reason I didn't before is b/c I was getting some unexpected results (I'm kinda new to lua, so some rules about scope and references vs copies are a bit confusing still). But I think I've got it working now, so here it is:

```lua
local function diagnostics()
    local errors = 0
    local warnings = 0

    local cur_buf_errors = 0
    local cur_buf_warnings = 0
    for _, buffer in ipairs(vim.fn['getbufinfo']()) do  -- Loop through buffers
        if buffer.listed == 1 and buffer.name ~= '' then  -- If the buffer is listed and it is not a no-name buffer
            local bufnr = buffer.bufnr
            local buf_errors = vim.lsp.diagnostic.get_count(bufnr, [[Error]])
            local buf_warnings = vim.lsp.diagnostic.get_count(bufnr, [[Warning]])
            errors = errors + buf_errors  -- Add this buffer's errors to the total errors
            warnings = warnings + buf_warnings  -- Same with warnings
            if bufnr == vim.fn.bufnr() then  -- If this buffer is the currently open buffer
                cur_buf_errors = buf_errors
                cur_buf_warnings = buf_warnings
            end
        end
    end
    if errors ~= 0 or warnings ~= 0 then  -- If there is at least one error or warning
        return "E "..tostring(cur_buf_errors)..":"..tostring(errors).." W "..tostring(cur_buf_warnings)..":"..tostring(warnings)
    else
        return ''  -- Otherwise return empty string
    end
end

```

**Comment by shadmansaleh** [comment]
```
vim.cmd('highlight my_hl_warn guifg=Orange')
vim.cmd('highlight my_hl_error guifg=Red')
local function diagnostics()
    local errors = 0
    local warnings = 0

    local cur_buf_errors = 0
    local cur_buf_warnings = 0
    for _, buffer in ipairs(vim.fn['getbufinfo']()) do  -- Loop through buffers
        if buffer.listed == 1 and buffer.name ~= '' then  -- If the buffer is listed and it is not a no-name buffer
            local bufnr = buffer.bufnr
            local buf_errors = vim.lsp.diagnostic.get_count(bufnr, [[Error]])
            local buf_warnings = vim.lsp.diagnostic.get_count(bufnr, [[Warning]])
            errors = errors + buf_errors  -- Add this buffer's errors to the total errors
            warnings = warnings + buf_warnings  -- Same with warnings
            if bufnr == vim.fn.bufnr() then  -- If this buffer is the currently open buffer
                cur_buf_errors = buf_errors
                cur_buf_warnings = buf_warnings
            end
        end
    end
    if errors ~= 0 or warnings ~= 0 then  -- If there is at least one error or warning
        return "%#my_hl_error#E "..tostring(cur_buf_errors)..":"..tostring(errors).." %#my_hl_warn#W "..tostring(cur_buf_warnings)..":"..tostring(warnings).."%#lualine_a_normal"
    else
        return ''  -- Otherwise return empty string
    end
end
```

Try this it will probably look weird on other modes . You can add a machanism to change lualine_a_normal to what mode you are on .

**Comment by pianocomposer321** [comment]
For postarity, this is what I ended up with:
![image](https://user-images.githubusercontent.com/54072354/105506979-45248780-5c90-11eb-8b9f-1c4f7b873161.png)

I'm likely gonna end up modularizing this a bit more, but for now, here's the [gist](https://gist.github.com/pianocomposer321/dd16eca88a588a233b7cbcb57039ed6e) of it 😉.

@hoob3rt some things I'd like to see change in lualine to make this type of thing easier (I'll open a separate issue for this if you want). I know that this project doesn't have to go the way I want it to, but these are just some suggestions, and I thought I should probably say them before the diagnostic section gets added and it's too late to make suggestions about how it should work.

 - (This one's obvious) there should be a section set aside for diagnostics. If it is pre-configured to show diagnostics already, it should be easy to substitute your own function to display them in the format you want.
 - There should be the ability to add your own sections/components to lualine. The problem with just adding a new function to existing sections is that it adds the separator between things, which messes up coloring (I'll attach a screenshot if you don't understand what I mean).

**Comment by shadmansaleh** [comment]
>there should be a section set aside for diagnostics. If it is pre-configured to show diagnostics already, it should be easy to substitute your own function to display them in the format you want.

I think we've decided to make it a genaral component that can be placed in any section.

>There should be the ability to add your own sections/components to lualine.

It's posible to add new components now it will be expanded with #53 .

> The problem with just adding a new function to existing sections is that it adds the separator between things, which messes up coloring (I'll attach a screenshot if you don't understand what I mean).

It shouldn't put a separator if it's returnes from same function . I'd love to see the screenshot please share it.

You can add suggetions to #38 that's where diagnostics is being discussed.

**Comment by pianocomposer321** [comment]
> It shouldn't put a separator if it's returnes from same function . I'd love to see the screenshot please share it.

![image](https://user-images.githubusercontent.com/54072354/105515213-098ebb00-5c9a-11eb-97ac-122d89191089.png)

It doesn't return from the same function...here's the part of my config where it's added to the statusline (note that this has been modified since I posted the gist):

```lua
    lualine.sections.lualine_z = vim.list_extend(lualine.sections.lualine_z, {
        function()
            local count = get_count()
            return diagnostics(count, {"", ""})
        end
    })
```

Here's a gist of the full config:
https://gist.github.com/pianocomposer321/1383f082ee1a41ab2cbd90d17d6534f3

**Comment by shadmansaleh** [comment]
>It doesn't return from the same function...here's the part of my config where it's added to the statusline

I get it now it's the separators between components. I thought you ment seperators inside a component. I think it looks bad because of the padding that is automaticaly added to components.

**Comment by pianocomposer321** [comment]
> > It doesn't return from the same function...here's the part of my config where it's added to the statusline
> 
> I get it now it's the separators between components. I thought you ment seperators inside a component. I think it looks bad because of the padding that is automaticaly added to components.

Yep, I'm pretty sure that's the problem.

**Comment by shadmansaleh** [comment]
For now since you want to have it in the end . You can just append it to statusline. Make your diagnostics function global and add this inplace of lualine.status() call

```lua
lualine.status()
vim.cmd("autocmd WinEnter,BufEnter * setlocal statusline=%!v:lua.set_active_statusline(1)..v:lua.diagnostics()")
```

Also remove diagnostics from z section.

**Comment by pianocomposer321** [comment]
Works great, thanks. Will do until this functionality gets added to lualine natively.

@hoob3rt @shadmansaleh Should this issue be close, or left open b/c lualine_diagnostics isn't implemented yet?

**Comment by hoob3rt** [comment]
Yeah, no point of having it open. I'm glad @shadmansaleh helped you implement the functionality you wanted. I will try to remember to tag you here when diagnostics is implemented natively
