### ISSUE TITLE
the git icon does not appear if I haven't installed kyazdani42/nvim-web-devicons

### ISSUE THREAD

**Issue by basilgood** [hoob3rt/lualine.nvim#78]
With nvim-web-devicons the icon appear without no.
I think it's from here: https://github.com/hoob3rt/lualine.nvim/blob/a2a9193296414aea13efa3a02fafb115f0226276/lua/lualine/components/branch.lua#L74
I'm don't know lua but if I switch ~= with == it works.

**Comment by shadmansaleh** [comment]
>With nvim-web-devicons the icon appear without no.

It's actualy a feature . Presence of nvim-web-devicons is used as an idicator thst user wants to see icons. It will be changed when #60 is merged you will be able to opt in or out of icons for each component.

>I'm don't know lua but if I switch ~= with == it works.
That means "show icon when nvim-web-devicons doesn't exist". you can remove the if statement in a local branch if you want to have icons unconditionaly. :)

**Comment by basilgood** [comment]
OK I understand. I thought that meant this: if there isn't nvim-web-devicons put this icon.
If I don't want nvim-web-devicons I still have an icon for git.
Feel free to close this issue.
