### ISSUE TITLE
Development paused/stopped?

### ISSUE THREAD

**Issue by coxackie** [hoob3rt/lualine.nvim#82]
It is the beginnings of the project, but somehow there is no movement for 10 days in terms of any updates. The PRs are more than the issue tickets. Is everything OK? I am not pressuring, I just want to make sure this did not become abandoned, as I really like this status line.

**Comment by hoob3rt** [comment]
Yeah development is paused. It will resume next week when I finish my exams :)

**Comment by coxackie** [comment]
thanks - good to know. and, of course, best of luck!
