### ISSUE TITLE
What's our approach on external plugin intigration?

### ISSUE THREAD

**Issue by shadmansaleh** [hoob3rt/lualine.nvim#85]
I personaly agree with 

>The lightline.vim plugin does not provide any plugin integration by default. This plugin considers orthogonality to be one of the important ideas, which means that the plugin does not rely on implementation of other plugins. Once a plugin starts to integrate with some famous plugins, it should be kept updated to follow the changes of the plugins, and should accept integration requests with new plugins and it will suffer from performance regression due to plugin availability checks.

from lightline.
Currently our only external dependecy is signify.
That's why I think it's a good time to disscuss it . Should we intrigrate directly with external plugins or should we give users flexible tools to use any plugin with lightline themselves?

**Comment by hoob3rt** [comment]
The lightline philosophy will be hard to come by when I eventually implement the diagnostics api(sorry it's taking so long). 

When we merge #53 there will be enough ways for users to integrate all their plugins into lualine. That said, I think some sane basics should be implemented (like our signify/diagnostics component). There is no need for every user to write the same components, the configuration of lualine should be as easy as it can get.

But about the signify compnent... This is a bad example of a sane basic. The feature it provides can surely be done without any dependencies. After #60 is done we can think about doing a git component like this ` {git, {branch, diff}}`.

Any reason why this question is being asked right now? Do you have some enhancement in mind?

**Comment by shadmansaleh** [comment]
>The lightline philosophy will be hard to come by when I eventually implement the diagnostics api(sorry it's taking so long).

Diagnostics api is probably few of those that most people will use. Also good portion of it will interect with intrigated-lsp-client so it might be able to squeeze in that philosophy.

>When we merge #53 there will be enough ways for users to integrate all their plugins into lualine. 

Agreed

>That said, I think some sane basics should be implemented (like our signify/diagnostics component). There is no need for every user to write the same components, the configuration of lualine should be as easy as it can get.
But about the signify compnent... This is a bad example of a sane basic. The feature it provides can surely be done without any dependencies. 

Dependency on signify can surely be removed . Apart from diagnostic api I cann't think of others that we directly need to provide . Say in airline they have tons of intogration with other plugins . Most those are useless to most of their users . Even if we add more dependency it should be kept at bare minimum for the sake of maintainability.
Like currently active issues #41 #42 #43 #44 I cann't actualy understand why they need to be added. 
say in #41 
>Statusline in fugitive window should display working git branch?

or #42
>Statusline in nerdtree window should display nerdtree's directory.

Normal statusline can do that why an extention?

I actually couldn't understand the whole extention section actualy. On my device fzf buffers open on a floating window without a statusline so I couldn't realy test out the fzf extention. But still I couldn't really think of use of it .

>After #60 is done we can think about doing a git component like this {git, {branch, diff}}.

This is a good idea.
>Do you have some enhancement in mind?

I actualy thought of implementing diff count in lualine and get rid of signify dependency . But even if I work on it it will be after #61 is merged . Resolving merge conflicts are getting realy tidious .
I merged #83 in #61 today but it was quite annoying as I had to rebase #60 on master then merge #60 to #61 .

**Comment by shadmansaleh** [comment]
>>After #60 is done we can think about doing a git component like this {git, {branch, diff}}.

>This is a good idea.

On second thought they are probably better of  separated . As they can be independently placed on statusline. Also being separate component will probably help with highlights.

**Comment by hoob3rt** [comment]
Yeah, I should probably resolve all piling pr's before thinking about doing a major change to these components.

**Comment by shadmansaleh** [comment]
>Yeah, I should probably resolve all piling pr's before thinking about doing a major change to these components.

Agreed.

**Comment by hoob3rt** [comment]
> I actually couldn't understand the whole extention section. On my device fzf buffers open on a floating window without a statusline So I couldn't really test out the fzf extention. But still I couldn't really think of use of it .

Well that's a late reply... sorry. Make fzf not floating and you will instantly get an idea on what extensions are for. I think it's an important part of the plugin although lacking right now
