### ISSUE TITLE
Tabline

### ISSUE THREAD

**Issue by shadmansaleh** [hoob3rt/lualine.nvim#89]
What do you think about using tabline?

Tabline and statusline use same formats right now you can do
```lua
vim.o.showtabline = 2
vim.o.tabline = vim.o.satusline
vim.o.statusline = ' '
```
And send statusline to top on vim . We could divide tabline into sections like statusline and allow users to put components to top of vim too. Say I could show stuff like mode and branch on top of vim insted of bottom ? We could probably also add a option to show traditional tabline too .

Oh I think the entire tabline should be optional . So users can use a different tabline plugin if they prefare it and not have two plugins fight over tabline😄

What do you think of the idea?

**Comment by hoob3rt** [comment]
Well I would rather stick to the unix philosophy. Do one thing and do it well. There are already existing lua implementations of tabline so I don't think it is necessary for us to implement it(Although the implementation would be minimal).

> show traditional tabline too

What do you have in mind? Is this not something a user can set without any plugin at all? Most themes already support tabline so I don't know what exactly are we supposed to do here?

I don't use tabline myself so I might be out of the loop. I am open to discussion here, feel free to prove my points wrong :)

**Comment by shadmansaleh** [comment]
>Well I would rather stick to the unix philosophy. Do one thing and do it well. There are already existing lua implementations of tabline so I don't think it is necessary for us to implement it(Although the implementation would be minimal).

My genaral idea wasn't to create a tabline but to allow users to extened their statusline to tabline to . By allowing components to be put on top of screen too . It can be done really simply . most of the stuff is already there . Will just have to add a in lualine.lua function that will call statusline function with a different tabline table and set that function as tabline . Just few li es of code.

 >>show traditional tabline too
>What do you have in mind? Is this not something a user can set without any plugin at all? Most themes already support tabline so I don't know what exactly are we supposed to do here?

>I don't use tabline myself so I might be out of the loop. I am open to discussion here, feel free to prove my points wrong :)

I personaly donn't use tab at all . So no use of tabline to me . That's why I'd like to move some stuff from statusline to top in tabline :)
