### ISSUE TITLE
Porting onedark colorscheme

### ISSUE THREAD

**Issue by teddylear** [hoob3rt/lualine.nvim#9]
Wanted to port over the onedark color scheme used in airline. Attached is PR with change with reference to onedark's airline code (note I could not find the colors for 'command' mode). Let me know if there are any questions or issues!

PR:  #8

**Comment by hoob3rt** [comment]
closed with https://github.com/hoob3rt/lualine.nvim/commit/08d2879f9b5839b1a05a659032dd33ebe1440485
