### ISSUE TITLE
Inactive component shows the current buffer's filename

### ISSUE THREAD

**Issue by yujinyuz** [hoob3rt/lualine.nvim#99]
[![asciicast](https://asciinema.org/a/qRwPE5gvg8vCK28zIgCLks6PV.svg)](https://asciinema.org/a/qRwPE5gvg8vCK28zIgCLks6PV)

**Comment by shadmansaleh** [comment]
Update to latest version it was fixed in #97. Thanks for reporting :)

**Comment by yujinyuz** [comment]
Thanks @shadmansaleh
